# Generated by Django 5.1.7 on 2025-03-30 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Tenant ID'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.UUIDField(blank=True, null=True, verbose_name='Owner ID'),
        ),
    ]
