# Generated by Django 5.0.6 on 2024-12-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='database_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='not_created', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='setup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=20),
        ),
    ]
