# Generated by Django 5.1.7 on 2025-03-25 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_tenant__d11818_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tenant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant_id'], name='users_userp_tenant__d11818_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['business_id'], name='users_userp_busines_4c5066_idx'),
        ),
    ]
