# Generated by Django 5.0.6 on 2025-01-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_database_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='database_status',
            field=models.CharField(choices=[('not_created', 'Not Created'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='not_created', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='setup_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=20),
        ),
    ]
