# Generated by Django 4.2.10 on 2025-07-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250715_0000'),  # Update this to your latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='simplified_business_type',
            field=models.CharField(
                blank=True, 
                choices=[
                    ('HOME_SERVICES', 'Home Services'),
                    ('CONSTRUCTION', 'Construction'),
                    ('CLEANING', 'Cleaning'),
                    ('AUTOMOTIVE_REPAIR', 'Automotive Repair'),
                    ('PROFESSIONAL_SERVICES', 'Professional Services'),
                    ('CREATIVE_SERVICES', 'Creative Services'),
                    ('RETAIL_STORE', 'Retail Store'),
                    ('RESTAURANT_CAFE', 'Restaurant/Cafe'),
                    ('GROCERY_MARKET', 'Grocery/Market'),
                    ('PHARMACY', 'Pharmacy'),
                    ('ONLINE_STORE', 'Online Store'),
                    ('SALON_SPA', 'Salon/Spa'),
                    ('MEDICAL_DENTAL', 'Medical/Dental'),
                    ('VETERINARY', 'Veterinary'),
                    ('FITNESS_CENTER', 'Fitness Center'),
                    ('AUTO_PARTS_REPAIR', 'Auto Parts & Repair'),
                    ('WAREHOUSE_STORAGE', 'Warehouse/Storage'),
                    ('MANUFACTURING', 'Manufacturing'),
                    ('LOGISTICS_FREIGHT', 'Logistics & Freight'),
                    ('FINANCIAL_SERVICES', 'Financial Services'),
                    ('REAL_ESTATE', 'Real Estate'),
                    ('AGRICULTURE', 'Agriculture'),
                    ('NON_PROFIT', 'Non-Profit'),
                    ('OTHER', 'Other'),
                ], 
                help_text='Simplified business category for feature access (Jobs/POS)', 
                max_length=50, 
                null=True
            ),
        ),
    ]