# Generated by Django 5.1.7 on 2025-04-21 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_schema_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuPrivilege',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_items', models.JSONField(default=list, help_text='List of menu items the user has access to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_privileges', to='users.businessmember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_privileges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_menu_privilege',
                'indexes': [models.Index(fields=['business_member'], name='users_menu__busines_f76fcb_idx')],
            },
        ),
    ]
