# Generated by Django 5.1.7 on 2025-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250330_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
