# Generated by Django 5.1.7 on 2025-03-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_owner_business_owner_id_and_more'),
    ]

    operations = [
    ]
