# Generated by Django 5.0.6 on 2024-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
