# Generated by Django 4.2.10 on 2025-07-26
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessdetails_simplified_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuVisibilitySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_item', models.CharField(max_length=100, help_text='Menu item identifier (e.g., jobs, pos, sales)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this menu item is visible')),
                ('parent_menu', models.CharField(blank=True, max_length=100, null=True, help_text='Parent menu identifier if this is a submenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_visibility_settings', to='users.business')),
            ],
            options={
                'db_table': 'users_menu_visibility_settings',
                'unique_together': {('business', 'menu_item')},
                'indexes': [models.Index(fields=['business', 'is_visible'], name='users_menu__busines_1a2b3c_idx')],
            },
        ),
    ]