# Generated by Django 4.2.16 on 2025-06-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_business_type_column'),
        ('users', '0005_add_stripe_subscription_id'),
    ]

    operations = [
    ]
