# Generated by Django 5.1.7 on 2025-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_occupation_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
    ]
