# Generated by Django 5.1.7 on 2025-04-21 16:15

from django.db import migrations


def convert_admin_to_owner(apps, schema_editor):
    """
    Convert any existing 'ADMIN' roles to 'owner' in the BusinessMember model
    """
    BusinessMember = apps.get_model('users', 'BusinessMember')
    admin_members = BusinessMember.objects.filter(role='ADMIN')
    print(f"Converting {admin_members.count()} ADMIN roles to owner roles")
    for member in admin_members:
        member.role = 'owner'
        member.save()


def convert_admin_back_to_admin(apps, schema_editor):
    """
    Reverse operation (not actually used, but required for reversible migrations)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250624_0122'),
    ]

    operations = [
        migrations.RunPython(convert_admin_to_owner, convert_admin_back_to_admin),
    ]
