# Generated by Django 4.2.16 on 2025-06-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_convert_admin_to_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
    ]
