# Generated by Django 5.1.7 on 2025-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fix_missing_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setup_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setup_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setup_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setup_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
