# Generated by Django 4.2.11 on 2025-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_stripe_connect_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(
                default='UTC',
                max_length=50,
                null=True,
                verbose_name='User Timezone',
                help_text='Timezone for displaying dates and times to the user'
            ),
        ),
    ]