# Generated by Django 4.2.11 on 2025-01-09 00:00
# NOTE: This migration was moved to custom_auth app where the User model actually lives
# See custom_auth/migrations/0002_add_user_timezone.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_stripe_connect_fields'),
    ]

    operations = [
        # Empty migration - timezone field moved to custom_auth.User model
    ]