# Generated by Django 4.2.11 on 2025-07-09 17:00
# This migration handles timezone field dependencies properly

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_stripe_connect_fields'),
        ('custom_auth', '0002_add_user_timezone'),  # Ensure custom_auth migration runs first
    ]

    operations = [
        # This migration is intentionally empty.
        # The timezone field was added in custom_auth.0002_add_user_timezone
        # This migration exists only to maintain proper dependency order.
    ]