# Generated by Django 5.1.7 on 2025-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_business_owner_id_userprofile_setup_completed_at_and_more'),
    ]

    operations = [
        # All operations have been merged into migration 0008
    ]
