# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile_show_whatsapp_commerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_legal_structure',
            field=models.BooleanField(default=True, help_text='Whether to show legal structure (LLC, Corp, Ltd) after business name in header'),
        ),
    ]