# Generated by Django 4.2.16 on 2025-07-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_menuvisibilitysettings'),
        ('users', '0019_add_business_settings'),
    ]

    operations = [
    ]
