# Generated by Django 4.2.9 on 2025-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20250727_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='logo',
            field=models.ImageField(
                blank=True,
                help_text='Business logo (max 5MB, JPG/PNG/GIF/WebP)',
                max_length=500,
                null=True,
                upload_to='business_logos/'
            ),
        ),
    ]