# Generated by Django 4.2.11 on 2025-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='preferred_currency_code',
            field=models.CharField(default='USD', help_text='3-letter ISO currency code (e.g., USD, EUR, KES)', max_length=3),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='preferred_currency_name',
            field=models.CharField(default='US Dollar', help_text='Full currency name', max_length=50),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='currency_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time currency was updated', null=True),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='show_usd_on_invoices',
            field=models.BooleanField(default=True, help_text='Show USD equivalent in parentheses on invoices'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='show_usd_on_quotes',
            field=models.BooleanField(default=True, help_text='Show USD equivalent in parentheses on quotes'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='show_usd_on_reports',
            field=models.BooleanField(default=False, help_text='Show USD equivalent in parentheses on reports'),
        ),
    ]