# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_business_currency_updated_at'),  # Adjust this to match your latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_zero_stock_pos',
            field=models.BooleanField(default=False, help_text='Whether to show products with zero stock in POS (for backorders)'),
        ),
    ]