# Generated by Django on 2025-09-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_auto_20250806_0000'),  # Adjust this to your latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.TextField(blank=True, help_text='Base64 encoded profile picture data URL', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time profile picture was updated', null=True),
        ),
    ]