# Generated by Django 5.2.5 on 2025-08-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_show_zero_stock_pos'),
        ('users', '0121_add_missing_currency_fields'),
    ]

    operations = [
    ]
