# Generated by Django on 2025-09-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_add_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='User location latitude for delivery and services', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='User location longitude for delivery and services', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='Location accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time location was updated', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_address',
            field=models.TextField(blank=True, help_text='Geocoded or user-provided address description', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easier delivery location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area_description',
            field=models.CharField(blank=True, help_text='Area or neighborhood description', max_length=200, null=True),
        ),
    ]