# Generated by Django 5.2.5 on 2025-09-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_currency_fields_to_userprofile'),
        ('users', '0132_populate_feature_modules'),
    ]

    operations = [
    ]
