services:
  - type: web
    name: dott-api
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements-render.txt && echo '=== Running Django Migrations ===' && python manage.py migrate --verbosity 2"
    startCommand: "./scripts/start.sh"
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pyfactor.settings
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1" 