from django.urls import path
from .views import (
    create_invoice,
    create_customer,
    customer_list,
    customer_detail,
    create_product,
    create_service,
    product_list,
    service_list,
    customer_invoices,
    customer_transactions,
    invoice_detail,
    invoice_list,
    update_customer,
    delete_customer,
    product_detail,
    service_detail,
    create_estimate,
    list_estimates,
    estimate_detail,
    update_estimate,
    delete_estimate,
    estimate_pdf,
    save_estimate,
    email_estimate,
    print_estimate,
    sales_order_detail,
    create_sales_order,
    list_sales_orders,
    income_by_customer,
    customer_income_detail,
    product_by_barcode,
    create_sale,
    print_barcode,

)

urlpatterns = [
    path('api/invoices/create/', create_invoice, name='invoice-create'),
    path('api/invoices/', invoice_list, name='invoice-list'),
    path('api/invoices/<uuid:pk>/', invoice_detail, name='invoice-detail'),    
    path('api/customers/create/', create_customer, name='create_customer'),
    path('api/customers/', customer_list, name='customer_list'),
    path('api/customers/<uuid:pk>/', customer_detail, name='customer-detail'),
    path('api/customers/<uuid:pk>/update/', update_customer, name='update-customer'),
    path('api/customers/<uuid:pk>/delete/', delete_customer, name='delete-customer'),
    path('api/products/create/', create_product, name='create_product'),
    path('api/services/create/', create_service, name='create_service'),
    path('api/products/', product_list, name='product_list'),
    path('api/products/<uuid:pk>/', product_detail, name='product-detail'),
    path('api/services/', service_list, name='service_list'),
    path('api/services/<uuid:pk>/', service_detail, name='service-detail'),
    path('api/customers/<uuid:customer_id>/invoices/', customer_invoices, name='customer-invoices'),
    path('api/customers/<uuid:customer_id>/transactions/', customer_transactions, name='customer-transactions'),
    path('api/estimates/create/', create_estimate, name='create-estimate'),
    path('api/estimates/', list_estimates, name='list-estimates'),
    path('api/estimates/<uuid:pk>/', estimate_detail, name='estimate-detail'),
    path('api/estimates/<uuid:pk>/update/', update_estimate, name='update-estimate'),
    path('api/estimates/<uuid:pk>/delete/', delete_estimate, name='delete-estimate'),
    path('api/estimates/<uuid:estimate_id>/pdf/', estimate_pdf, name='estimate_pdf'),
    path('api/estimates/<uuid:estimate_id>/save/', save_estimate, name='save_estimate'),
    path('api/estimates/<uuid:estimate_id>/print/', print_estimate, name='print_estimate'),
    path('api/estimates/<uuid:estimate_id>/email/', email_estimate, name='email_estimate'),
    path('api/salesorders/create/', create_sales_order, name='create-sales-order'),
    path('api/salesorders/', list_sales_orders, name='list-sales-orders'),
    path('api/salesorders/<uuid:pk>/', sales_order_detail, name='sales-order-detail'),
    path('api/income-by-customer/', income_by_customer, name='income-by-customer'),
    path('api/income-by-customer/<uuid:customer_id>/', customer_income_detail, name='customer-income-detail'),
    path('api/products/barcode/<str:barcode>/', product_by_barcode, name='product-by-barcode'),
    path('api/sales/create/', create_sale, name='create-sale'),
    path('api/products/<uuid:product_id>/print-barcode/', print_barcode, name='print-barcode'),


]