from django.urls import path
from .views import (
    create_invoice,
    create_customer,
    customer_list,
    customer_detail,
    create_product,
    create_service,
    create_vendor,
    product_list,
    service_list,
    customer_invoices,
    customer_transactions,
    invoice_detail,
    update_customer,
    delete_customer,
    product_detail,
    service_detail,
    create_estimate,  # Updated
    list_estimates,   # Updated
    estimate_detail,
    update_estimate,
    delete_estimate,
    create_bill,
    vendor_list,
    estimate_pdf,
    save_estimate,
    email_estimate,
    print_estimate,
    sales_order_detail,
    sales_order_list_create,
)

urlpatterns = [
    path('api/invoices/', create_invoice, name='invoice-create'),
    path('api/customers/create/', create_customer, name='create_customer'),
    path('api/customers/', customer_list, name='customer_list'),
    path('api/customers/<uuid:pk>/', customer_detail, name='customer-detail'),
    path('api/customers/<uuid:pk>/update/', update_customer, name='update-customer'),
    path('api/customers/<uuid:pk>/delete/', delete_customer, name='delete-customer'),
    path('api/products/create/', create_product, name='create_product'),
    path('api/services/create/', create_service, name='create_service'),
    path('api/vendors/create/', create_vendor, name='create_vendor'),
    path('api/products/', product_list, name='product_list'),
    path('api/products/<uuid:pk>/', product_detail, name='product-detail'),
    path('api/services/', service_list, name='service_list'),
    path('api/services/<uuid:pk>/', service_detail, name='service-detail'),
    path('api/customers/<uuid:customer_id>/invoices/', customer_invoices, name='customer-invoices'),
    path('api/customers/<uuid:customer_id>/transactions/', customer_transactions, name='customer-transactions'),
    path('api/invoices/<uuid:invoice_id>/', invoice_detail, name='invoice-detail'),
    path('api/estimates/create/', create_estimate, name='create-estimate'),  # Updated
    path('api/estimates/', list_estimates, name='list-estimates'),           # Updated
    path('api/estimates/<uuid:pk>/', estimate_detail, name='estimate-detail'),
    path('api/estimates/<uuid:pk>/update/', update_estimate, name='update-estimate'),
    path('api/estimates/<uuid:pk>/delete/', delete_estimate, name='delete-estimate'),
    path('api/bills/', create_bill, name='create_bill'),
    path('api/vendors/', vendor_list, name='vendor_list'),
    path('api/estimates/<uuid:estimate_id>/pdf/', estimate_pdf, name='estimate_pdf'),
    path('api/estimates/<uuid:estimate_id>/save/', save_estimate, name='save_estimate'),
    path('api/estimates/<uuid:estimate_id>/print/', print_estimate, name='print_estimate'),
    path('api/estimates/<uuid:estimate_id>/email/', email_estimate, name='email_estimate'),
    path('api/salesorders/', sales_order_list_create, name='sales_order_list_create'),
    path('api/salesorders/<uuid:pk>/', sales_order_detail, name='sales_order_detail'),
]
