# Generated by Django 5.1.7 on 2025-04-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='compensation_type',
            field=models.CharField(choices=[('SALARY', 'Salary (Yearly)'), ('WAGE', 'Wage (Hourly)')], default='SALARY', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_filing_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married Filing Jointly'), ('MS', 'Married Filing Separately'), ('H', 'Head of Household')], max_length=2, null=True),
        ),
    ]
