# Generated by Django 5.0.6 on 2025-02-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='security_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tax_id_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_stored_in_stripe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssn_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssn_stored_in_stripe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='stripe_person_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_id_stored_in_stripe',
            field=models.BooleanField(default=False),
        ),
    ]
