# Generated by Django 5.0.6 on 2024-09-06 12:22

import django.core.validators
import django.db.models.deletion
import hr.custom_fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=hr.custom_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time')], default='FT', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_insurance_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reason_for_leaving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_number',
            field=hr.custom_fields.EncryptedCharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_number_type',
            field=models.CharField(choices=[('SSN', 'Social Security Number (US)'), ('NIN', 'National Insurance Number (UK)'), ('SIN', 'Social Insurance Number (Canada)'), ('TFN', 'Tax File Number (Australia)'), ('NRIC', 'National Registration Identity Card (Singapore)'), ('AADHAAR', 'Aadhaar Number (India)'), ('CPF', 'CPF Number (Brazil)'), ('CURP', 'CURP (Mexico)'), ('DNI', 'DNI Number (Spain, Argentina, Peru)'), ('HKID', 'Hong Kong Identity Card'), ('NINO', 'National Identity Number (Sweden)'), ('BSN', 'Citizen Service Number (Netherlands)'), ('PESEL', 'PESEL Number (Poland)'), ('RUT', 'RUT Number (Chile)'), ('CNIC', 'CNIC Number (Pakistan)'), ('GSTIN', 'GSTIN Number (India for businesses)'), ('MYKAD', 'MyKad Number (Malaysia)'), ('KTP', 'KTP Number (Indonesia)'), ('PAN', 'PAN Card Number (India)'), ('NIF', 'NIF Number (Portugal)'), ('STCN', 'Social Tag Card Number (China)'), ('IRD', 'IRD Number (New Zealand)'), ('PPS', 'PPS Number (Ireland)'), ('NPWP', 'NPWP Number (Indonesia for tax)'), ('CUIT', 'CUIT Number (Argentina)'), ('IQAMA', 'Iqama Number (Saudi Arabia)'), ('EKTP', 'eKTP Number (Indonesia)'), ('NIS', 'NIS Number (Brazil)'), ('KITAS', 'KITAS Number (Indonesia for foreigners)'), ('OTHER', 'Other National ID')], default='SSN', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_filing_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married Filing Jointly'), ('S', 'Married Filing Separately'), ('H', 'Head of Household')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_id_number',
            field=hr.custom_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
