# Generated by Django 5.1.7 on 2025-04-21 16:16

from django.db import migrations


def convert_admin_to_owner(apps, schema_editor):
    """
    Convert any existing 'ADMIN' roles to 'owner' in the Employee model
    """
    Employee = apps.get_model('hr', 'Employee')
    admin_employees = Employee.objects.filter(role='ADMIN')
    print(f"Converting {admin_employees.count()} ADMIN roles to owner roles in Employee model")
    for employee in admin_employees:
        employee.role = 'owner'
        employee.save()


def convert_admin_back_to_admin(apps, schema_editor):
    """
    Reverse operation (not actually used, but required for reversible migrations)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_compensation_type_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_admin_to_owner, convert_admin_back_to_admin),
    ]
