# Generated by Django 5.0.6 on 2024-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_bank_account_number_employee_days_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
