# Generated by Django 5.0.6 on 2025-02-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_wallet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_wallet_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
