# Generated by Django 5.1.7 on 2025-03-24 21:45
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Check and fix the role column
            DO $$
            BEGIN
                -- First check if the role column exists
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'hr_employee' AND column_name = 'role'
                ) THEN
                    -- Column exists, ensure it has the right type and values
                    ALTER TABLE hr_employee ALTER COLUMN role TYPE varchar(20) USING role::varchar(20);
                    
                    -- Update any NULL values to 'EMPLOYEE'
                    UPDATE hr_employee SET role = 'EMPLOYEE' WHERE role IS NULL;
                ELSE
                    -- Column doesn't exist, add it
                    ALTER TABLE hr_employee ADD COLUMN role varchar(20) DEFAULT 'EMPLOYEE';
                END IF;
                
                -- Check if site_access_privileges column exists 
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'hr_employee' AND column_name = 'site_access_privileges'
                ) THEN
                    -- Try to convert to jsonb if not already
                    BEGIN
                        ALTER TABLE hr_employee 
                        ALTER COLUMN site_access_privileges TYPE jsonb 
                        USING CASE 
                            WHEN site_access_privileges IS NULL THEN '[]'::jsonb
                            ELSE site_access_privileges::jsonb 
                        END;
                    EXCEPTION WHEN others THEN
                        -- If conversion fails, drop and recreate
                        ALTER TABLE hr_employee DROP COLUMN site_access_privileges;
                        ALTER TABLE hr_employee ADD COLUMN site_access_privileges jsonb DEFAULT '[]'::jsonb;
                    END;
                ELSE
                    -- Add the column if it doesn't exist
                    ALTER TABLE hr_employee ADD COLUMN site_access_privileges jsonb DEFAULT '[]'::jsonb;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- No reverse SQL needed as we're just ensuring correct column types
            """
        ),
    ]
