# Generated by Django 5.0.6

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_employee_tenant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('CLOCK_IN', 'Clock In'), ('CLOCK_OUT', 'Clock Out'), ('RANDOM_CHECK', 'Random Check'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End')], max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Location accuracy in meters', max_digits=10, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('formatted_address', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_method', models.CharField(blank=True, max_length=50, null=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Location Log',
                'verbose_name_plural': 'Location Logs',
                'ordering': ['-logged_at'],
                'indexes': [
                    models.Index(fields=['employee', 'logged_at'], name='hr_location_employe_8e7e91_idx'),
                    models.Index(fields=['business_id', 'location_type', 'logged_at'], name='hr_location_busines_e9e814_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLocationConsent',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('has_consented', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('revoked_date', models.DateTimeField(blank=True, null=True)),
                ('allow_clock_in_out_tracking', models.BooleanField(default=True)),
                ('allow_random_checks', models.BooleanField(default=False)),
                ('allow_continuous_tracking', models.BooleanField(default=False)),
                ('share_with_manager', models.BooleanField(default=True)),
                ('share_with_hr', models.BooleanField(default=True)),
                ('consent_version', models.CharField(default='1.0', help_text='Version of privacy policy/terms accepted', max_length=20)),
                ('ip_address_at_consent', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_consent', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Employee Location Consent',
                'verbose_name_plural': 'Employee Location Consents',
            },
        ),
        migrations.CreateModel(
            name='LocationCheckIn',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in_location_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_checkins', to='hr.locationlog')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_location', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Location Check In',
                'verbose_name_plural': 'Location Check Ins',
            },
        ),
        migrations.AddField(
            model_name='locationlog',
            name='timesheet_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to='hr.timesheetentry'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='clock_in_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_in_entries', to='hr.locationlog'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='clock_out_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_out_entries', to='hr.locationlog'),
        ),
    ]