# Generated by Django 3.2.25 on 2025-01-10 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_add_location_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('OFFICE', 'Office Building'), ('CONSTRUCTION', 'Construction Site'), ('CLIENT', 'Client Location'), ('DELIVERY', 'Delivery Zone'), ('FIELD', 'Field Location'), ('CUSTOM', 'Custom Location')], default='OFFICE', max_length=20)),
                ('shape_type', models.CharField(choices=[('CIRCLE', 'Circle'), ('POLYGON', 'Polygon')], default='CIRCLE', max_length=20)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('radius_meters', models.IntegerField(default=200, help_text='Radius in meters for circle type')),
                ('address', models.TextField(blank=True, null=True)),
                ('polygon_points', models.JSONField(blank=True, help_text='Array of lat/lng points for polygon', null=True)),
                ('require_for_clock_in', models.BooleanField(default=True)),
                ('require_for_clock_out', models.BooleanField(default=False)),
                ('auto_clock_out_on_exit', models.BooleanField(default=False)),
                ('alert_on_unexpected_exit', models.BooleanField(default=False)),
                ('track_time_inside', models.BooleanField(default=True)),
                ('notify_manager_on_entry', models.BooleanField(default=False)),
                ('notify_manager_on_exit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_geofences', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Geofence',
                'verbose_name_plural': 'Geofences',
                'unique_together': {('business_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('ENTER', 'Entered Geofence'), ('EXIT', 'Exited Geofence'), ('CLOCK_IN', 'Clocked In'), ('CLOCK_OUT', 'Clocked Out'), ('VIOLATION', 'Geofence Violation')], max_length=20)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('distance_from_center', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in meters from geofence center', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='hr.employee')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.geofence')),
                ('location_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_events', to='hr.locationlog')),
            ],
            options={
                'verbose_name': 'Geofence Event',
                'verbose_name_plural': 'Geofence Events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGeofence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('can_clock_in_outside', models.BooleanField(default=False, help_text='Override geofence requirement')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_assignments_made', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_geofences', to='hr.employee')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='hr.geofence')),
            ],
            options={
                'verbose_name': 'Employee Geofence',
                'verbose_name_plural': 'Employee Geofences',
                'unique_together': {('employee', 'geofence')},
            },
        ),
    ]