# Generated by Django 5.0.6 on 2024-06-26 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_userprofile_database_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('BS', 'Balance Sheet'), ('CF', 'Cash Flow Statement'), ('IS', 'Income Statement')], max_length=2)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
