# Generated by Django 5.0.6 on 2024-06-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0004_alter_userprofile_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.userprofile'),
        ),
    ]
