# Generated by Django 5.0.6 on 2024-06-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_user_profile'),
        ('users', '0004_alter_userprofile_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('BS', 'Balance Sheet'), ('CF', 'Cash Flow'), ('IS', 'Income Statement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
