# Generated by Django 5.0.6 on 2024-07-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('bigcommerce', 'BigCommerce'), ('prestashop', 'PrestaShop'), ('squarespace', 'Squarespace'), ('wix', 'Wix eCommerce'), ('opencart', 'OpenCart'), ('volusion', 'Volusion'), ('3dcart', '3dcart (Shift4Shop)'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('store_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WooCommerceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WooCommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField()),
                ('billing', models.JSONField()),
                ('shipping', models.JSONField()),
                ('line_items', models.JSONField(default=dict)),
            ],
        ),
    ]
