# Generated by Django 5.0.6 on 2024-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('bigcommerce', 'BigCommerce'), ('prestashop', 'PrestaShop'), ('squarespace', 'Squarespace'), ('wix', 'Wix eCommerce'), ('opencart', 'OpenCart'), ('volusion', 'Volusion'), ('3dcart', '3dcart (Shift4Shop)')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('store_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shopify_customers',
            },
        ),
        migrations.CreateModel(
            name='ShopifyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.URLField(unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token_last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('financial_status', models.CharField(max_length=50)),
                ('fulfillment_status', models.CharField(max_length=50)),
                ('customer_id', models.BigIntegerField()),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
            ],
            options={
                'db_table': 'shopify_orders',
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
                ('variant_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shopify_order_items',
            },
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('vendor', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('template_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('published_scope', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_graphql_api_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shopify_products',
            },
        ),
        migrations.CreateModel(
            name='WooCommerceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WooCommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField()),
                ('billing', models.JSONField()),
                ('shipping', models.JSONField()),
                ('line_items', models.JSONField(default=dict)),
            ],
        ),
    ]
