# Generated by Django 5.0.6 on 2024-07-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='woocommerceintegration',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_integration', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='integrations.woocommerceintegration'),
        ),
    ]
