# Generated by Django 5.0.6 on 2024-08-31 18:44

import django.db.models.deletion
import integrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='shopifyintegration',
            name='user',
            field=models.ForeignKey(default=integrations.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifycustomer',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='integrations.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='integrations.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifyorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.shopifyorder'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='integrations.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='woocommerceintegration',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_integration', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='integrations.woocommerceintegration'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyintegration',
            unique_together={('user', 'shop_url')},
        ),
    ]
