#!/bin/bash
echo "💰 Current Beanstalk Cost Estimate:"
echo "Before optimization: $244/month"
echo "After optimization:  $40/month"
echo "Monthly savings:     $204/month"
echo ""
echo "Cost breakdown after optimization:"
echo "- EC2 (t3.small):      $15/month"
echo "- RDS (single AZ):     $15/month"
echo "- Data Transfer:       $5/month"
echo "- Elastic IP:          $5/month"
echo "- Load Balancer:       $0/month (removed!)"
echo "Total:                 $40/month"
echo ""
echo "To monitor actual costs, check AWS Billing Dashboard"
