#!/bin/bash

echo "🚀 Backend Deployment Guide for Render"
echo "====================================="
echo ""
echo "Your backend is currently NOT running the latest code with the tenant lookup fix."
echo ""
echo "The fix (commit 6b885bcc) converts user.id to string when querying for tenants."
echo ""
echo "To deploy the backend with the fix:"
echo ""
echo "Option 1: Auto-deploy (if GitHub is connected):"
echo "1. Ensure your Render service is connected to the GitHub repo"
echo "2. Set it to auto-deploy from the 'Dott_Main_Dev_Deploy' branch"
echo "3. The deployment should trigger automatically"
echo ""
echo "Option 2: Manual deploy:"
echo "1. Go to https://dashboard.render.com/"
echo "2. Find your backend service (api.dottapps.com)"
echo "3. Click on the service"
echo "4. Go to 'Settings' tab"
echo "5. Scroll to 'Build & Deploy' section"
echo "6. Click 'Manual Deploy' > 'Deploy latest commit'"
echo ""
echo "Option 3: Using Render CLI (if installed):"
echo "render deploy --service-id <your-service-id>"
echo ""
echo "📋 What to look for after deployment:"
echo "- The deployment logs should show it's building from commit 6b885bcc or later"
echo "- Once deployed, the backend logs should show:"
echo "  '🔥 [USER_PROFILE] Tenant lookup by owner_id ('17') result: <Tenant instance>'"
echo "  instead of 'None'"
echo ""
echo "🔍 To verify the deployment worked:"
echo "1. Clear your browser cache"
echo "2. Sign in with kdeng@dottapps.com"
echo "3. You should go directly to the dashboard, NOT to onboarding"
echo ""
echo "Current issue: The backend is querying owner_id=17 but the database has owner_id='17' (string)"