-- Create AdminUser for notification system admin portal
-- This directly inserts into the admin_users table

INSERT INTO admin_users (
    id,
    username,
    email,
    password,
    first_name,
    last_name,
    is_active,
    employee_id,
    department,
    admin_role,
    can_send_notifications,
    can_view_all_users,
    can_view_feedback,
    can_moderate_content,
    ip_whitelist,
    phone_number,
    slack_user_id,
    last_login,
    last_login_ip,
    failed_login_attempts,
    account_locked_until,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'admin',
    'kdeng@dottapps.com',
    'pbkdf2_sha256$600000$yMQsK3xUBnA2YyN1KfJfKP$FZjRzxX2n6XJYnLs1HZnXJNzZnZnXJYnXJYnXJY=', -- password: admin123 (hashed)
    'Admin',
    'User',
    true,
    'ADMIN001',
    'management',
    'super_admin',
    true,
    true,
    true,
    true,
    '[]'::json,
    '',
    '',
    NULL,
    NULL,
    0,
    NULL,
    NOW(),
    NOW()
) ON CONFLICT (username) DO NOTHING;

-- Also create one with email conflict handling
INSERT INTO admin_users (
    id,
    username,
    email,
    password,
    first_name,
    last_name,
    is_active,
    employee_id,
    department,
    admin_role,
    can_send_notifications,
    can_view_all_users,
    can_view_feedback,
    can_moderate_content,
    ip_whitelist,
    phone_number,
    slack_user_id,
    last_login,
    last_login_ip,
    failed_login_attempts,
    account_locked_until,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'kdeng',
    'k.deng@dottapps.com',
    'pbkdf2_sha256$600000$yMQsK3xUBnA2YyN1KfJfKP$FZjRzxX2n6XJYnLs1HZnXJNzZnZnXJYnXJYnXJY=', -- password: admin123 (hashed)
    'Kevin',
    'Deng',
    true,
    'OWNER001',
    'management',
    'super_admin',
    true,
    true,
    true,
    true,
    '[]'::json,
    '',
    '',
    NULL,
    NULL,
    0,
    NULL,
    NOW(),
    NOW()
) ON CONFLICT (username) DO NOTHING;