#!/bin/bash

echo "🔧 Production Migration Fix Script"
echo "================================="
echo ""
echo "Run these commands in your Render shell:"
echo ""
echo "1. Fake the problematic RBAC migration:"
echo "   python manage.py migrate custom_auth 0012_add_rbac_models --fake"
echo ""
echo "2. Run all remaining migrations:"
echo "   python manage.py migrate"
echo ""
echo "3. Verify notifications tables were created:"
echo "   python manage.py dbshell"
echo "   \\dt *notification*"
echo "   \\dt *admin*"
echo "   \\q"
echo ""
echo "✅ This will complete the notification system deployment!"