#!/bin/bash

echo "🔍 Monitoring Sales Dashboard Debug Logs"
echo "========================================="
echo ""
echo "This script will help you monitor the logs to debug the Sales Dashboard issue."
echo ""
echo "📝 Steps to monitor logs:"
echo ""
echo "1. FRONTEND LOGS (Render):"
echo "   - Go to https://dashboard.render.com"
echo "   - Open 'dott-front' service"
echo "   - Click on 'Logs' tab"
echo "   - Look for lines starting with '[Sales-Data Route]'"
echo ""
echo "2. BACKEND LOGS (Render):"
echo "   - Go to https://dashboard.render.com"
echo "   - Open 'dott-api' service"
echo "   - Click on 'Logs' tab"
echo "   - Look for lines starting with '[SALES-DATA-API]'"
echo ""
echo "3. KEY THINGS TO LOOK FOR:"
echo "   - Session ID validation"
echo "   - Database name resolution"
echo "   - User tenant_id"
echo "   - Query results (POS transactions and invoices count)"
echo "   - Response status codes"
echo "   - Error messages and stack traces"
echo ""
echo "4. REPRODUCE THE ISSUE:"
echo "   - Go to https://staging.dottapps.com"
echo "   - Navigate to Sales Dashboard"
echo "   - Watch the logs in real-time"
echo ""
echo "5. COMMON ISSUES TO CHECK:"
echo "   - Missing session cookie (authentication issue)"
echo "   - Database name is 'None' (tenant resolution issue)"
echo "   - HTML response instead of JSON (middleware issue)"
echo "   - 400/401/403 errors (permission issue)"
echo "   - 500 errors (backend exception)"
echo ""
echo "The detailed logging will show exactly where the request is failing."
echo ""
echo "✅ Deployment should be complete in about 60 seconds."