#!/bin/bash

echo "📋 Commands to run on your Render backend shell:"
echo "=============================================="
echo ""
echo "1. First, SSH into your Render backend (you've already done this)"
echo ""
echo "2. Navigate to the Django app directory:"
echo "   cd /app/backend/pyfactor"
echo ""
echo "3. Run the debug script to see what's in the database:"
echo "   python debug_tenant_lookup.py"
echo ""
echo "4. Run the fix script to create/fix the tenant:"
echo "   python fix_tenant_owner_id.py"
echo ""
echo "5. (Optional) Test the fix by running the debug script again:"
echo "   python debug_tenant_lookup.py"
echo ""
echo "That's it! After running these, sign out and sign back in to test."