#!/bin/bash

echo "🔍 Quick Tenant Lookup Fix Verification"
echo "======================================"
echo ""
echo "To verify if the fix is deployed, do ONE of these:"
echo ""
echo "1. Check Render deployment info:"
echo "   - Go to https://dashboard.render.com/"
echo "   - Click on your backend service"
echo "   - Check the 'Events' tab for the latest deployment"
echo "   - Look for commit hash starting with '6b885bcc' or later"
echo ""
echo "2. Test directly:"
echo "   - Clear your browser cache"
echo "   - Sign in to https://app.dottapps.com with kdeng@dottapps.com"
echo "   - If you go to dashboard = ✅ Fix deployed"
echo "   - If you go to onboarding = ❌ Fix NOT deployed"
echo ""
echo "3. SSH into Render and check the code:"
echo "   ssh srv-xxxxx@ssh.oregon.render.com"
echo "   cd /app/backend/pyfactor"
echo "   grep -n 'user_id_str = str(user.id)' custom_auth/api/views/auth0_views.py"
echo ""
echo "If you see the grep results with line numbers, the fix is deployed!"