# Generated by Django 5.0.6 on 2024-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
