# Generated by Django 5.2.5 on 2025-09-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_fix_consumer_profile_json_fields'),
        ('marketplace', '0008_add_payment_delivery_fields'),
    ]

    operations = [
    ]
