# Generated by Django 5.2.5 on 2025-09-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_add_pickup_pin'),
        ('marketplace', '0015_add_service_fee_field'),
    ]

    operations = [
    ]
