# Generated by Django 5.1.7 on 2025-04-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='schema_name',
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='users.business'),
        ),
    ]
