# Generated by Django 5.1.7 on 2025-03-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer'), ('van', 'Van'), ('forklift', 'Forklift'), ('container', 'Container'), ('other', 'Other')], max_length=100, verbose_name='Vehicle Type'),
        ),
    ]
