# Generated by Django 4.2.16 on 2025-06-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0002_enhanced_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='device_fing_user_id_438bf4_idx',
            old_name='device_fing_user_id_6a3c3f_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='device_fing_fingerp_25f02a_idx',
            old_name='device_fing_fingerp_8c3d77_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='device_fing_risk_sc_fa51cb_idx',
            old_name='device_fing_risk_sc_f4a2b8_idx',
        ),
        migrations.RenameIndex(
            model_name='devicetrust',
            new_name='device_trus_user_id_051562_idx',
            old_name='device_trus_user_id_8a2c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionsecurity',
            new_name='session_sec_current_e1668b_idx',
            old_name='session_sec_current_d9c4a1_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionsecurity',
            new_name='session_sec_last_he_00323f_idx',
            old_name='session_sec_last_he_7f8b9c_idx',
        ),
    ]
