# Generated by Django 4.2.16 on 2025-06-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_timesta_be67a1_idx',
            old_name='audit_log_timesta_1b0f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_model_n_c04ad8_idx',
            old_name='audit_log_model_n_d9c8f1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_tenant__ae62a1_idx',
            old_name='audit_log_tenant__e7c9a5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_action_09d227_idx',
            old_name='audit_log_action_8b4f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_request_a46c86_idx',
            old_name='audit_log_request_3f8a2d_idx',
        ),
    ]
