# Generated by Django 4.2.16 on 2025-06-29 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_insights', '0002_add_balance_before_and_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyusage',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RemoveIndex(
            model_name='credittransaction',
            name='smart_insig_user_id_2a9876_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyusage',
            name='smart_insig_user_id_4e5678_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercredit',
            name='smart_insig_user_id_credit_idx',
        ),
        migrations.RenameIndex(
            model_name='querylog',
            new_name='smart_insig_user_id_da3238_idx',
            old_name='smart_insig_user_id_3e1234_idx',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='package',
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, default=''),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, default=''),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_insights_credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
