# Generated by Django 5.1.7 on 2025-04-16 17:23

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_created_at_supplier_is_active_and_more'),
    ]

    operations = [
        # This is a special operation that will run a raw SQL to check if the column already exists
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'inventory_supplier' AND column_name = 'tenant_id'
                ) THEN
                    ALTER TABLE inventory_supplier ADD COLUMN tenant_id UUID NULL;
                    CREATE INDEX ON inventory_supplier (tenant_id, name);
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- No need for reverse SQL as we won't drop the column
            """
        ),
        # Still add the field to the model so Django knows about it
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No actual database changes
            state_operations=[
                migrations.AddField(
                    model_name='supplier',
                    name='tenant_id',
                    field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
                ),
                migrations.AddIndex(
                    model_name='supplier',
                    index=models.Index(fields=['tenant_id', 'name'], name='inventory_s_tenant__e764cc_idx'),
                ),
            ],
        ),
    ]
