# Generated by Django 5.1.7 on 2025-04-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billingCountry',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billingState',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerName',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='deliveryInstructions',
            new_name='delivery_instructions',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='shipToName',
            new_name='ship_to_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='shippingCountry',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='shippingPhone',
            new_name='shipping_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='shippingState',
            new_name='shipping_state',
        ),
    ]
