# Generated by Django 5.0.6 on 2025-02-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('nutritional_info', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('load_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_fields', to='sales.product')),
            ],
            options={
                'verbose_name': 'Product Type Field',
                'verbose_name_plural': 'Product Type Fields',
            },
        ),
        migrations.CreateModel(
            name='ServiceTypeFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('min_booking_notice', models.DurationField(blank=True, null=True)),
                ('buffer_time', models.DurationField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_requirements', models.TextField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_fields', to='sales.service')),
            ],
            options={
                'verbose_name': 'Service Type Field',
                'verbose_name_plural': 'Service Type Fields',
            },
        ),
    ]
