# Generated by Django 5.0.6 on 2024-06-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_due_date_invoice_status_invoice_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accountNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billingCountry',
            field=models.CharField(default='United States', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='billingState',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='customerName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='deliveryInstructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='primaryContactEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='primaryContactFirstName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='primaryContactLastName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='primaryContactPhone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipToName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shippingCountry',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shippingPhone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shippingState',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
