# Generated by Django 5.0.6 on 2024-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
