# Generated by Django 4.2.16 on 2025-06-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_missing_fields_and_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='estimate',
            new_name='sales_estim_tenant__bfa1b9_idx',
            old_name='sales_estimate_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='estimateattachment',
            new_name='sales_estim_tenant__4ef6c8_idx',
            old_name='sales_estimateattach_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='estimateitem',
            new_name='sales_estim_tenant__be23e5_idx',
            old_name='sales_estimateitem_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceitem',
            new_name='sales_invoi_tenant__56f28e_idx',
            old_name='sales_invoiceitem_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='sales_refun_tenant__3a5d5b_idx',
            old_name='sales_refund_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='refunditem',
            new_name='sales_refun_tenant__03bb89_idx',
            old_name='sales_refunditem_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='salesproduct',
            new_name='sales_produ_tenant__e30f33_idx',
            old_name='sales_product_tenant_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='salestax',
            new_name='sales_tax_tenant__15ec7f_idx',
            old_name='sales_tax_tenant_name_idx',
        ),
    ]
