# Generated by Django 5.0.6 on 2024-08-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorderitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
