# Generated by Django 5.0.6 on 2024-09-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_incomebycustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeByCustomer',
        ),
    ]
