# Generated by Django 5.0.6 on 2024-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_estimateitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
