# Generated by Django 5.0.6 on 2024-08-24 14:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_estimate_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
