# Generated by Django migration to add missing SalesOrder fields

from django.db import migrations, models
import django.utils.timezone
import uuid


def default_due_datetime():
    """Default due date is 30 days from now"""
    from datetime import datetime, timedelta
    return (datetime.now().date() + timedelta(days=30))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_salesorder_due_date'),
    ]

    operations = [
        # Check and add missing fields to sales_salesorder table
        # This migration safely adds fields that may be missing
        
        # payment_terms field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='payment_terms'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN payment_terms VARCHAR(50) DEFAULT 'net_30';
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS payment_terms;
            """
        ),
        
        # due_date field (in case previous migration didn't run)
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='due_date'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN due_date DATE DEFAULT CURRENT_DATE + INTERVAL '30 days';
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS due_date;
            """
        ),
        
        # subtotal field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='subtotal'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN subtotal DECIMAL(19,4) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS subtotal;
            """
        ),
        
        # tax_total field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='tax_total'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN tax_total DECIMAL(19,4) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS tax_total;
            """
        ),
        
        # tax_rate field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='tax_rate'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN tax_rate DECIMAL(5,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS tax_rate;
            """
        ),
        
        # discount_percentage field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='discount_percentage'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN discount_percentage DECIMAL(5,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS discount_percentage;
            """
        ),
        
        # shipping_cost field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='shipping_cost'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN shipping_cost DECIMAL(10,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS shipping_cost;
            """
        ),
        
        # total field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='total'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN total DECIMAL(19,4) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS total;
            """
        ),
        
        # total_amount field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='total_amount'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN total_amount DECIMAL(19,4) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS total_amount;
            """
        ),
        
        # notes field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='notes'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN notes TEXT;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS notes;
            """
        ),
        
        # estimate_id field (foreign key to estimate)
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorder' 
                    AND column_name='estimate_id'
                ) THEN
                    ALTER TABLE sales_salesorder 
                    ADD COLUMN estimate_id UUID;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorder DROP COLUMN IF EXISTS estimate_id;
            """
        ),
    ]