# Generated by Django 5.0.6 on 2024-09-02 14:09

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_delete_incomebycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=sales.models.default_due_datetime),
        ),
    ]
