# Generated by Django 5.0.6 on 2024-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_amount_given_sale_change_due_sale_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='buyEnabled',
            new_name='is_for_rent',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='buyEnabled',
            new_name='is_for_rent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sellEnabled',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sellEnabled',
        ),
        migrations.AddField(
            model_name='product',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='charge_period',
            field=models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('in', 'Inch')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('lb', 'Pound'), ('g', 'Gram')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('in', 'Inch')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='charge_period',
            field=models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('in', 'Inch')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('lb', 'Pound'), ('g', 'Gram')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('in', 'Inch')], default='cm', max_length=10),
        ),
    ]
