# Generated by Django 5.0.6 on 2024-08-24 15:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_estimate_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
