# Generated by Django migration to add missing SalesOrderItem fields

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_missing_salesorder_fields'),
    ]

    operations = [
        # Check and add missing fields to sales_salesorderitem table
        # This migration safely adds fields that may be missing
        
        # item_type field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='item_type'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN item_type VARCHAR(20) DEFAULT 'product';
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS item_type;
            """
        ),
        
        # product_id field (foreign key to product)
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='product_id'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN product_id UUID;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS product_id;
            """
        ),
        
        # service_id field (foreign key to service)
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='service_id'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN service_id UUID;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS service_id;
            """
        ),
        
        # item_id field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='item_id'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN item_id VARCHAR(100);
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS item_id;
            """
        ),
        
        # description field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='description'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN description VARCHAR(200);
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS description;
            """
        ),
        
        # quantity field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='quantity'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN quantity DECIMAL(10,2) DEFAULT 1;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS quantity;
            """
        ),
        
        # unit_price field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='unit_price'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN unit_price DECIMAL(10,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS unit_price;
            """
        ),
        
        # tax_rate field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='tax_rate'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN tax_rate DECIMAL(5,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS tax_rate;
            """
        ),
        
        # tax_amount field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='tax_amount'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN tax_amount DECIMAL(10,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS tax_amount;
            """
        ),
        
        # total field
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='sales_salesorderitem' 
                    AND column_name='total'
                ) THEN
                    ALTER TABLE sales_salesorderitem 
                    ADD COLUMN total DECIMAL(10,2) DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE sales_salesorderitem DROP COLUMN IF EXISTS total;
            """
        ),
    ]