# Generated by Django 5.0.6 on 2024-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_invoice_refund_refunditem_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomChargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('unit', 'Per Unit'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('custom', 'Custom')], max_length=10)),
                ('custom_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('custom', 'Custom')], max_length=10)),
                ('custom_period', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='custom_charge_plans',
            field=models.ManyToManyField(blank=True, to='sales.customchargeplan'),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_charge_plans',
            field=models.ManyToManyField(blank=True, to='sales.customchargeplan'),
        ),
    ]
