# Generated by Django 5.0.6 on 2024-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_estimate_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_num',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
