# Generated by Django 5.0.6 on 2024-06-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_customer_currency_alter_customer_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billingCountry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billingState',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primaryContactFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primaryContactLastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
