# Generated by Django 4.2.16 on 2025-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_missing_salesorderitem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_terms',
            field=models.CharField(default='net_30', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
