# Generated by Django 5.0.6 on 2024-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_estimate_estimate_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
