# Generated by Django 5.0.6 on 2024-08-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesorder_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='amount',
        ),
    ]
