# Generated by Django 5.0.6 on 2024-06-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='primaryContactFirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='primaryContactLastName',
            new_name='last_name',
        ),
    ]
