# Generated by Django 5.0.6 on 2024-06-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rename_primarycontactfirstname_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='primaryContactEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='primaryContactPhone',
            new_name='phone',
        ),
    ]
