# Generated by Django 5.0.6 on 2024-08-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_currency_invoice_discount_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='totalAmount',
        ),
    ]
