# Generated by Django 5.0.6 on 2024-06-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='Enter City', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(default='Enter State', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='postcode',
            field=models.CharField(default='Enter Postcode', max_length=10),
        ),
    ]
