# Generated by Django 5.0.6 on 2024-06-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_vendor_city_vendor_phone_vendor_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='accounts_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_receivable', to='sales.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cost_of_goods_sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_cogs', to='sales.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_inventory', to='sales.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_revenue', to='sales.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_tax_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_tax_payable', to='sales.account'),
        ),
    ]
