# Generated by Django 5.0.6 on 2024-06-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_account_invoice_accounts_receivable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='product_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='sales.product'),
        ),
    ]
