# Generated by Django 5.0.6 on 2024-06-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_invoice'),
        ('sales', '0015_alter_department_product_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cost_of_goods_sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_cogs', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='accounts_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_receivable', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_inventory', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_tax_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_tax_payable', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_revenue', to='finance.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
