# Generated by Django 5.0.6 on 2024-06-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_account_created_at_and_more'),
        ('sales', '0017_remove_bill_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='accounts_receivable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_receivable', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cost_of_goods_sold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_cogs', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_inventory', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_revenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_revenue', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_tax_payable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_tax_payable', to='finance.account'),
        ),
    ]
