# Generated by Django 5.1.7 on 2025-03-29 19:51

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('service_type', models.CharField(choices=[('full', 'Full-Service'), ('self', 'Self-Service')], default='self', max_length=10)),
                ('compliance_last_checked', models.DateTimeField(blank=True, null=True)),
                ('compliance_check_frequency', models.IntegerField(default=30)),
                ('full_service_enabled', models.BooleanField(default=False, help_text='Whether Dott provides full tax filing service for this state')),
                ('e_file_supported', models.BooleanField(default=False, help_text='Whether this state supports electronic filing')),
                ('e_file_portal_url', models.URLField(blank=True, null=True)),
                ('has_local_taxes', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=50)),
                ('payroll_run', models.CharField(db_index=True, max_length=50)),
                ('filing_period_start', models.DateField()),
                ('filing_period_end', models.DateField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('filing_status', models.CharField(choices=[('preparation', 'In Preparation'), ('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='preparation', max_length=20)),
                ('total_wages', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_withholding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confirmation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_method', models.CharField(choices=[('api', 'Direct API'), ('portal', 'State Portal'), ('manual', 'Manual Filing'), ('self_service', 'Self-Service by Customer')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tax_filings/%Y/%m/')),
                ('is_amended', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to='taxes.state')),
            ],
        ),
        migrations.CreateModel(
            name='TaxApiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_payload', models.TextField()),
                ('response_payload', models.TextField()),
                ('status_code', models.IntegerField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_transactions', to='taxes.state')),
            ],
        ),
        migrations.CreateModel(
            name='TaxFilingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('portal_url', models.URLField()),
                ('filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('due_days', models.IntegerField(help_text='Days after period end when filing is due')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filing_instructions', to='taxes.state')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('is_flat_rate', models.BooleanField(default=False)),
                ('rate_value', models.DecimalField(decimal_places=4, help_text='Tax rate as a decimal (e.g. 0.0525 for 5.25%)', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('income_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('married_joint', 'Married Filing Jointly'), ('married_separate', 'Married Filing Separately'), ('head_household', 'Head of Household')], default='single', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manual_override', models.BooleanField(default=False, help_text='Set to True if this rate was manually updated')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='taxes.state')),
            ],
            options={
                'unique_together': {('state', 'tax_year', 'filing_status', 'income_min')},
            },
        ),
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField(blank=True, null=True)),
                ('form_type', models.CharField(choices=[('W2', 'W-2 Wage and Tax Statement'), ('W4', 'W-4 Employee Withholding Certificate'), ('1099', '1099-MISC Miscellaneous Income'), ('1095C', '1095-C Employer-Provided Health Insurance'), ('940', 'Form 940 Federal Unemployment Tax'), ('941', 'Form 941 Quarterly Federal Tax Return'), ('STATE_WH', 'State Withholding Form'), ('OTHER', 'Other Tax Form')], max_length=20)),
                ('tax_year', models.IntegerField()),
                ('filing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('employer_id_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='tax_forms/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_employer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('was_filed', models.BooleanField(default=False)),
                ('filing_confirmation', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tax_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee_id', 'form_type', 'tax_year')},
            },
        ),
    ]
