# Generated by Django 5.0.6 on 2025-02-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='compliance_check_frequency',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='state',
            name='compliance_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='service_type',
            field=models.CharField(choices=[('full', 'Full-Service'), ('self', 'Self-Service')], default='self', max_length=10),
        ),
    ]
