# Generated by Django 4.2.16 on 2025-06-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_taxsettings_taxratecache_taxapiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reminder_type', models.CharField(choices=[('sales_tax', 'Sales Tax'), ('income_tax', 'Income Tax'), ('quarterly', 'Quarterly Filing'), ('annual', 'Annual Filing'), ('other', 'Other')], max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tax_reminders',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['tenant_id', 'due_date'], name='tax_reminde_tenant__c58185_idx'), models.Index(fields=['tenant_id', 'status'], name='tax_reminde_tenant__516c65_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxFilingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('federal_website', models.URLField(blank=True, default='', max_length=500)),
                ('federal_name', models.CharField(blank=True, default='', max_length=255)),
                ('federal_address', models.TextField(blank=True, default='')),
                ('federal_phone', models.CharField(blank=True, default='', max_length=50)),
                ('federal_email', models.EmailField(blank=True, default='', max_length=254)),
                ('state_website', models.URLField(blank=True, default='', max_length=500)),
                ('state_name', models.CharField(blank=True, default='', max_length=255)),
                ('state_address', models.TextField(blank=True, default='')),
                ('state_phone', models.CharField(blank=True, default='', max_length=50)),
                ('state_email', models.EmailField(blank=True, default='', max_length=254)),
                ('local_website', models.URLField(blank=True, default='', max_length=500)),
                ('local_name', models.CharField(blank=True, default='', max_length=255)),
                ('local_address', models.TextField(blank=True, default='')),
                ('local_phone', models.CharField(blank=True, default='', max_length=50)),
                ('local_email', models.EmailField(blank=True, default='', max_length=254)),
                ('filing_deadlines', models.JSONField(blank=True, default=dict)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('tax_types', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('lookup_count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tax_filing_locations',
                'indexes': [models.Index(fields=['country', 'state_province'], name='tax_filing__country_42de96_idx'), models.Index(fields=['last_updated'], name='tax_filing__last_up_c90f92_idx'), models.Index(fields=['lookup_count'], name='tax_filing__lookup__8c0de4_idx')],
                'unique_together': {('country', 'state_province', 'city')},
            },
        ),
    ]
