# Generated by Django 5.2.5 on 2025-08-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_tax_accounting_models'),
        ('taxes', '0022_add_county_filing_fields'),
    ]

    operations = [
    ]
