# Generated by Django 5.1.7 on 2025-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='empl', max_length=50),
        ),
    ]
