const fs = require('fs');
const path = require('path');

// POS translations for all 20 languages
const translations = {
  es: { // Spanish
    "title": "Sistema de Punto de Venta",
    "searchProducts": "Buscar productos por nombre, SKU o código de barras...",
    "scanProduct": "Escanear Producto",
    "addProduct": "Agregar Producto",
    "clearCart": "Vaciar Carrito",
    "emptyCart": "No hay artículos en el carrito",
    "customer": "Cliente",
    "walkInCustomer": "Cliente sin cita",
    "selectCustomer": "Seleccionar cliente para esta venta (opcional)",
    "discount": "Descuento",
    "applyDiscount": "Aplicar descuento al subtotal",
    "percentage": "Porcentaje",
    "amount": "Cantidad",
    "taxRate": "Tasa de Impuesto (%)",
    "taxRateTooltip": "Tasa de impuesto aplicada al subtotal con descuento",
    "paymentMethod": "Método de Pago",
    "paymentMethodTooltip": "Seleccionar método de pago",
    "cash": "Efectivo",
    "card": "Tarjeta",
    "creditCard": "Tarjeta de Crédito",
    "debitCard": "Tarjeta de Débito",
    "mobilePayment": "Pago Móvil",
    "other": "Otro",
    "notes": "Notas",
    "notesTooltip": "Agregar notas para esta venta (opcional)",
    "subtotal": "Subtotal",
    "tax": "Impuesto",
    "total": "Total",
    "processSale": "Procesar Venta",
    "processing": "Procesando...",
    "quantity": "Cantidad",
    "price": "Precio",
    "stock": "Inventario",
    "inStock": "en inventario",
    "remove": "Eliminar",
    "productDetails": "Detalles del Producto",
    "sku": "SKU",
    "barcode": "Código de Barras",
    "notAvailable": "N/D",
    "inventoryUpdated": "Inventario actualizado automáticamente",
    "accountingEntriesCreated": "Entradas contables registradas",
    "saleCompleted": "¡Venta completada exitosamente!",
    "error": "Error",
    "loadingProducts": "Cargando productos desde la base de datos...",
    "errorLoadingProducts": "Error al Cargar Productos",
    "reload": "Recargar",
    "searchResults": "Resultados de Búsqueda:",
    "noProductsFound": "No se encontraron productos",
    "clearSearch": "Limpiar búsqueda",
    "processingQRCode": "Procesando datos del código QR...",
    "scannerDetection": "Detección de Escáner",
    "scannerDetectionMessage": "Conecte un escáner de código de barras USB y escanee un producto para habilitar la detección automática.",
    "cameraPermission": "Permiso de Cámara",
    "allowCameraAccess": "Por favor, permita el acceso a la cámara para escanear códigos QR",
    "scanningProduct": "Escaneando producto...",
    "positionQRCode": "Posicione el código QR dentro del marco",
    "productAdded": "Producto agregado al carrito",
    "close": "Cerrar"
  },
  fr: { // French
    "title": "Système de Point de Vente",
    "searchProducts": "Rechercher des produits par nom, SKU ou code-barres...",
    "scanProduct": "Scanner le Produit",
    "addProduct": "Ajouter le Produit",
    "clearCart": "Vider le Panier",
    "emptyCart": "Aucun article dans le panier",
    "customer": "Client",
    "walkInCustomer": "Client de passage",
    "selectCustomer": "Sélectionner le client pour cette vente (optionnel)",
    "discount": "Remise",
    "applyDiscount": "Appliquer une remise au sous-total",
    "percentage": "Pourcentage",
    "amount": "Montant",
    "taxRate": "Taux de Taxe (%)",
    "taxRateTooltip": "Taux de taxe appliqué au sous-total avec remise",
    "paymentMethod": "Mode de Paiement",
    "paymentMethodTooltip": "Sélectionner le mode de paiement",
    "cash": "Espèces",
    "card": "Carte",
    "creditCard": "Carte de Crédit",
    "debitCard": "Carte de Débit",
    "mobilePayment": "Paiement Mobile",
    "other": "Autre",
    "notes": "Notes",
    "notesTooltip": "Ajouter des notes pour cette vente (optionnel)",
    "subtotal": "Sous-total",
    "tax": "Taxe",
    "total": "Total",
    "processSale": "Traiter la Vente",
    "processing": "Traitement...",
    "quantity": "Quantité",
    "price": "Prix",
    "stock": "Stock",
    "inStock": "en stock",
    "remove": "Retirer",
    "productDetails": "Détails du Produit",
    "sku": "SKU",
    "barcode": "Code-barres",
    "notAvailable": "N/D",
    "inventoryUpdated": "Inventaire mis à jour automatiquement",
    "accountingEntriesCreated": "Écritures comptables enregistrées",
    "saleCompleted": "Vente complétée avec succès!",
    "error": "Erreur",
    "loadingProducts": "Chargement des produits depuis la base de données...",
    "errorLoadingProducts": "Erreur lors du Chargement des Produits",
    "reload": "Recharger",
    "searchResults": "Résultats de Recherche:",
    "noProductsFound": "Aucun produit trouvé",
    "clearSearch": "Effacer la recherche",
    "processingQRCode": "Traitement des données du code QR...",
    "scannerDetection": "Détection du Scanner",
    "scannerDetectionMessage": "Connectez un scanner de code-barres USB et scannez un produit pour activer la détection automatique.",
    "cameraPermission": "Permission de la Caméra",
    "allowCameraAccess": "Veuillez autoriser l'accès à la caméra pour scanner les codes QR",
    "scanningProduct": "Scan du produit...",
    "positionQRCode": "Positionnez le code QR dans le cadre",
    "productAdded": "Produit ajouté au panier",
    "close": "Fermer"
  },
  de: { // German
    "title": "Kassensystem",
    "searchProducts": "Produkte nach Name, SKU oder Barcode suchen...",
    "scanProduct": "Produkt Scannen",
    "addProduct": "Produkt Hinzufügen",
    "clearCart": "Warenkorb Leeren",
    "emptyCart": "Keine Artikel im Warenkorb",
    "customer": "Kunde",
    "walkInCustomer": "Laufkunde",
    "selectCustomer": "Kunde für diesen Verkauf auswählen (optional)",
    "discount": "Rabatt",
    "applyDiscount": "Rabatt auf Zwischensumme anwenden",
    "percentage": "Prozent",
    "amount": "Betrag",
    "taxRate": "Steuersatz (%)",
    "taxRateTooltip": "Steuersatz auf rabattierte Zwischensumme angewendet",
    "paymentMethod": "Zahlungsmethode",
    "paymentMethodTooltip": "Zahlungsmethode auswählen",
    "cash": "Bargeld",
    "card": "Karte",
    "creditCard": "Kreditkarte",
    "debitCard": "Debitkarte",
    "mobilePayment": "Mobile Zahlung",
    "other": "Sonstige",
    "notes": "Notizen",
    "notesTooltip": "Notizen für diesen Verkauf hinzufügen (optional)",
    "subtotal": "Zwischensumme",
    "tax": "Steuer",
    "total": "Gesamt",
    "processSale": "Verkauf Verarbeiten",
    "processing": "Verarbeitung...",
    "quantity": "Menge",
    "price": "Preis",
    "stock": "Lagerbestand",
    "inStock": "auf Lager",
    "remove": "Entfernen",
    "productDetails": "Produktdetails",
    "sku": "SKU",
    "barcode": "Barcode",
    "notAvailable": "N/V",
    "inventoryUpdated": "Inventar automatisch aktualisiert",
    "accountingEntriesCreated": "Buchhaltungseinträge erfasst",
    "saleCompleted": "Verkauf erfolgreich abgeschlossen!",
    "error": "Fehler",
    "loadingProducts": "Produkte werden aus der Datenbank geladen...",
    "errorLoadingProducts": "Fehler beim Laden der Produkte",
    "reload": "Neu laden",
    "searchResults": "Suchergebnisse:",
    "noProductsFound": "Keine Produkte gefunden",
    "clearSearch": "Suche löschen",
    "processingQRCode": "QR-Code-Daten werden verarbeitet...",
    "scannerDetection": "Scanner-Erkennung",
    "scannerDetectionMessage": "Schließen Sie einen USB-Barcode-Scanner an und scannen Sie ein Produkt, um die automatische Erkennung zu aktivieren.",
    "cameraPermission": "Kamera-Berechtigung",
    "allowCameraAccess": "Bitte erlauben Sie den Kamerazugriff zum Scannen von QR-Codes",
    "scanningProduct": "Produkt wird gescannt...",
    "positionQRCode": "Positionieren Sie den QR-Code im Rahmen",
    "productAdded": "Produkt zum Warenkorb hinzugefügt",
    "close": "Schließen"
  },
  pt: { // Portuguese
    "title": "Sistema de Ponto de Venda",
    "searchProducts": "Pesquisar produtos por nome, SKU ou código de barras...",
    "scanProduct": "Escanear Produto",
    "addProduct": "Adicionar Produto",
    "clearCart": "Limpar Carrinho",
    "emptyCart": "Nenhum item no carrinho",
    "customer": "Cliente",
    "walkInCustomer": "Cliente sem marcação",
    "selectCustomer": "Selecionar cliente para esta venda (opcional)",
    "discount": "Desconto",
    "applyDiscount": "Aplicar desconto ao subtotal",
    "percentage": "Percentagem",
    "amount": "Valor",
    "taxRate": "Taxa de Imposto (%)",
    "taxRateTooltip": "Taxa de imposto aplicada ao subtotal com desconto",
    "paymentMethod": "Método de Pagamento",
    "paymentMethodTooltip": "Selecionar método de pagamento",
    "cash": "Dinheiro",
    "card": "Cartão",
    "creditCard": "Cartão de Crédito",
    "debitCard": "Cartão de Débito",
    "mobilePayment": "Pagamento Móvel",
    "other": "Outro",
    "notes": "Notas",
    "notesTooltip": "Adicionar notas para esta venda (opcional)",
    "subtotal": "Subtotal",
    "tax": "Imposto",
    "total": "Total",
    "processSale": "Processar Venda",
    "processing": "Processando...",
    "quantity": "Quantidade",
    "price": "Preço",
    "stock": "Estoque",
    "inStock": "em estoque",
    "remove": "Remover",
    "productDetails": "Detalhes do Produto",
    "sku": "SKU",
    "barcode": "Código de Barras",
    "notAvailable": "N/D",
    "inventoryUpdated": "Inventário atualizado automaticamente",
    "accountingEntriesCreated": "Lançamentos contábeis registrados",
    "saleCompleted": "Venda concluída com sucesso!",
    "error": "Erro",
    "loadingProducts": "Carregando produtos do banco de dados...",
    "errorLoadingProducts": "Erro ao Carregar Produtos",
    "reload": "Recarregar",
    "searchResults": "Resultados da Pesquisa:",
    "noProductsFound": "Nenhum produto encontrado",
    "clearSearch": "Limpar pesquisa",
    "processingQRCode": "Processando dados do código QR...",
    "scannerDetection": "Detecção de Scanner",
    "scannerDetectionMessage": "Conecte um scanner de código de barras USB e escaneie um produto para ativar a detecção automática.",
    "cameraPermission": "Permissão da Câmera",
    "allowCameraAccess": "Por favor, permita o acesso à câmera para escanear códigos QR",
    "scanningProduct": "Escaneando produto...",
    "positionQRCode": "Posicione o código QR dentro do quadro",
    "productAdded": "Produto adicionado ao carrinho",
    "close": "Fechar"
  },
  ru: { // Russian
    "title": "Кассовая Система",
    "searchProducts": "Поиск товаров по названию, артикулу или штрих-коду...",
    "scanProduct": "Сканировать Товар",
    "addProduct": "Добавить Товар",
    "clearCart": "Очистить Корзину",
    "emptyCart": "В корзине нет товаров",
    "customer": "Клиент",
    "walkInCustomer": "Разовый покупатель",
    "selectCustomer": "Выберите клиента для этой продажи (необязательно)",
    "discount": "Скидка",
    "applyDiscount": "Применить скидку к промежуточному итогу",
    "percentage": "Процент",
    "amount": "Сумма",
    "taxRate": "Налоговая Ставка (%)",
    "taxRateTooltip": "Налоговая ставка применяется к промежуточному итогу со скидкой",
    "paymentMethod": "Способ Оплаты",
    "paymentMethodTooltip": "Выберите способ оплаты",
    "cash": "Наличные",
    "card": "Карта",
    "creditCard": "Кредитная Карта",
    "debitCard": "Дебетовая Карта",
    "mobilePayment": "Мобильный Платеж",
    "other": "Другое",
    "notes": "Примечания",
    "notesTooltip": "Добавить примечания для этой продажи (необязательно)",
    "subtotal": "Промежуточный итог",
    "tax": "Налог",
    "total": "Итого",
    "processSale": "Обработать Продажу",
    "processing": "Обработка...",
    "quantity": "Количество",
    "price": "Цена",
    "stock": "Запас",
    "inStock": "в наличии",
    "remove": "Удалить",
    "productDetails": "Детали Товара",
    "sku": "Артикул",
    "barcode": "Штрих-код",
    "notAvailable": "Н/Д",
    "inventoryUpdated": "Инвентарь обновлен автоматически",
    "accountingEntriesCreated": "Бухгалтерские записи созданы",
    "saleCompleted": "Продажа успешно завершена!",
    "error": "Ошибка",
    "loadingProducts": "Загрузка товаров из базы данных...",
    "errorLoadingProducts": "Ошибка Загрузки Товаров",
    "reload": "Перезагрузить",
    "searchResults": "Результаты Поиска:",
    "noProductsFound": "Товары не найдены",
    "clearSearch": "Очистить поиск",
    "processingQRCode": "Обработка данных QR-кода...",
    "scannerDetection": "Обнаружение Сканера",
    "scannerDetectionMessage": "Подключите USB-сканер штрих-кодов и отсканируйте товар для включения автоматического обнаружения.",
    "cameraPermission": "Разрешение Камеры",
    "allowCameraAccess": "Пожалуйста, разрешите доступ к камере для сканирования QR-кодов",
    "scanningProduct": "Сканирование товара...",
    "positionQRCode": "Расположите QR-код в рамке",
    "productAdded": "Товар добавлен в корзину",
    "close": "Закрыть"
  },
  ja: { // Japanese
    "title": "POSシステム",
    "searchProducts": "商品名、SKU、バーコードで検索...",
    "scanProduct": "商品をスキャン",
    "addProduct": "商品を追加",
    "clearCart": "カートをクリア",
    "emptyCart": "カートに商品がありません",
    "customer": "顧客",
    "walkInCustomer": "来店客",
    "selectCustomer": "この販売の顧客を選択（任意）",
    "discount": "割引",
    "applyDiscount": "小計に割引を適用",
    "percentage": "パーセント",
    "amount": "金額",
    "taxRate": "税率（％）",
    "taxRateTooltip": "割引後の小計に適用される税率",
    "paymentMethod": "支払方法",
    "paymentMethodTooltip": "支払方法を選択",
    "cash": "現金",
    "card": "カード",
    "creditCard": "クレジットカード",
    "debitCard": "デビットカード",
    "mobilePayment": "モバイル決済",
    "other": "その他",
    "notes": "メモ",
    "notesTooltip": "この販売のメモを追加（任意）",
    "subtotal": "小計",
    "tax": "税",
    "total": "合計",
    "processSale": "販売処理",
    "processing": "処理中...",
    "quantity": "数量",
    "price": "価格",
    "stock": "在庫",
    "inStock": "在庫あり",
    "remove": "削除",
    "productDetails": "商品詳細",
    "sku": "SKU",
    "barcode": "バーコード",
    "notAvailable": "N/A",
    "inventoryUpdated": "在庫が自動的に更新されました",
    "accountingEntriesCreated": "会計記録が作成されました",
    "saleCompleted": "販売が正常に完了しました！",
    "error": "エラー",
    "loadingProducts": "データベースから商品を読み込んでいます...",
    "errorLoadingProducts": "商品の読み込みエラー",
    "reload": "再読み込み",
    "searchResults": "検索結果：",
    "noProductsFound": "商品が見つかりません",
    "clearSearch": "検索をクリア",
    "processingQRCode": "QRコードデータを処理中...",
    "scannerDetection": "スキャナー検出",
    "scannerDetectionMessage": "USBバーコードスキャナーを接続し、商品をスキャンして自動検出を有効にしてください。",
    "cameraPermission": "カメラ許可",
    "allowCameraAccess": "QRコードをスキャンするためにカメラへのアクセスを許可してください",
    "scanningProduct": "商品をスキャン中...",
    "positionQRCode": "QRコードをフレーム内に配置してください",
    "productAdded": "商品がカートに追加されました",
    "close": "閉じる"
  },
  ko: { // Korean
    "title": "POS 시스템",
    "searchProducts": "상품명, SKU 또는 바코드로 검색...",
    "scanProduct": "제품 스캔",
    "addProduct": "제품 추가",
    "clearCart": "장바구니 비우기",
    "emptyCart": "장바구니에 상품이 없습니다",
    "customer": "고객",
    "walkInCustomer": "방문 고객",
    "selectCustomer": "이 판매의 고객 선택 (선택 사항)",
    "discount": "할인",
    "applyDiscount": "소계에 할인 적용",
    "percentage": "백분율",
    "amount": "금액",
    "taxRate": "세율 (%)",
    "taxRateTooltip": "할인된 소계에 적용되는 세율",
    "paymentMethod": "결제 방법",
    "paymentMethodTooltip": "결제 방법 선택",
    "cash": "현금",
    "card": "카드",
    "creditCard": "신용카드",
    "debitCard": "직불카드",
    "mobilePayment": "모바일 결제",
    "other": "기타",
    "notes": "메모",
    "notesTooltip": "이 판매에 대한 메모 추가 (선택 사항)",
    "subtotal": "소계",
    "tax": "세금",
    "total": "합계",
    "processSale": "판매 처리",
    "processing": "처리 중...",
    "quantity": "수량",
    "price": "가격",
    "stock": "재고",
    "inStock": "재고 있음",
    "remove": "제거",
    "productDetails": "제품 상세",
    "sku": "SKU",
    "barcode": "바코드",
    "notAvailable": "N/A",
    "inventoryUpdated": "재고가 자동으로 업데이트되었습니다",
    "accountingEntriesCreated": "회계 항목이 기록되었습니다",
    "saleCompleted": "판매가 성공적으로 완료되었습니다!",
    "error": "오류",
    "loadingProducts": "데이터베이스에서 제품을 로드하는 중...",
    "errorLoadingProducts": "제품 로드 오류",
    "reload": "다시 로드",
    "searchResults": "검색 결과:",
    "noProductsFound": "제품을 찾을 수 없습니다",
    "clearSearch": "검색 지우기",
    "processingQRCode": "QR 코드 데이터 처리 중...",
    "scannerDetection": "스캐너 감지",
    "scannerDetectionMessage": "USB 바코드 스캐너를 연결하고 제품을 스캔하여 자동 감지를 활성화하세요.",
    "cameraPermission": "카메라 권한",
    "allowCameraAccess": "QR 코드를 스캔하려면 카메라 액세스를 허용하세요",
    "scanningProduct": "제품 스캔 중...",
    "positionQRCode": "프레임 내에 QR 코드를 배치하세요",
    "productAdded": "제품이 장바구니에 추가되었습니다",
    "close": "닫기"
  },
  zh: { // Chinese
    "title": "销售点系统",
    "searchProducts": "按名称、SKU或条形码搜索产品...",
    "scanProduct": "扫描产品",
    "addProduct": "添加产品",
    "clearCart": "清空购物车",
    "emptyCart": "购物车中没有商品",
    "customer": "客户",
    "walkInCustomer": "临时客户",
    "selectCustomer": "为此次销售选择客户（可选）",
    "discount": "折扣",
    "applyDiscount": "对小计应用折扣",
    "percentage": "百分比",
    "amount": "金额",
    "taxRate": "税率（%）",
    "taxRateTooltip": "对折扣后小计应用的税率",
    "paymentMethod": "付款方式",
    "paymentMethodTooltip": "选择付款方式",
    "cash": "现金",
    "card": "卡",
    "creditCard": "信用卡",
    "debitCard": "借记卡",
    "mobilePayment": "移动支付",
    "other": "其他",
    "notes": "备注",
    "notesTooltip": "为此次销售添加备注（可选）",
    "subtotal": "小计",
    "tax": "税",
    "total": "总计",
    "processSale": "处理销售",
    "processing": "处理中...",
    "quantity": "数量",
    "price": "价格",
    "stock": "库存",
    "inStock": "有货",
    "remove": "删除",
    "productDetails": "产品详情",
    "sku": "SKU",
    "barcode": "条形码",
    "notAvailable": "不适用",
    "inventoryUpdated": "库存已自动更新",
    "accountingEntriesCreated": "会计分录已记录",
    "saleCompleted": "销售成功完成！",
    "error": "错误",
    "loadingProducts": "正在从数据库加载产品...",
    "errorLoadingProducts": "加载产品时出错",
    "reload": "重新加载",
    "searchResults": "搜索结果：",
    "noProductsFound": "未找到产品",
    "clearSearch": "清除搜索",
    "processingQRCode": "正在处理二维码数据...",
    "scannerDetection": "扫描仪检测",
    "scannerDetectionMessage": "连接USB条形码扫描仪并扫描产品以启用自动检测。",
    "cameraPermission": "相机权限",
    "allowCameraAccess": "请允许相机访问以扫描二维码",
    "scanningProduct": "正在扫描产品...",
    "positionQRCode": "将二维码置于框架内",
    "productAdded": "产品已添加到购物车",
    "close": "关闭"
  },
  ar: { // Arabic
    "title": "نظام نقطة البيع",
    "searchProducts": "البحث عن المنتجات بالاسم أو SKU أو الباركود...",
    "scanProduct": "مسح المنتج",
    "addProduct": "إضافة منتج",
    "clearCart": "إفراغ السلة",
    "emptyCart": "لا توجد منتجات في السلة",
    "customer": "العميل",
    "walkInCustomer": "عميل عابر",
    "selectCustomer": "اختر العميل لهذا البيع (اختياري)",
    "discount": "خصم",
    "applyDiscount": "تطبيق خصم على المجموع الفرعي",
    "percentage": "نسبة مئوية",
    "amount": "مبلغ",
    "taxRate": "معدل الضريبة (%)",
    "taxRateTooltip": "معدل الضريبة المطبق على المجموع الفرعي بعد الخصم",
    "paymentMethod": "طريقة الدفع",
    "paymentMethodTooltip": "اختر طريقة الدفع",
    "cash": "نقدي",
    "card": "بطاقة",
    "creditCard": "بطاقة ائتمان",
    "debitCard": "بطاقة خصم",
    "mobilePayment": "دفع عبر الجوال",
    "other": "أخرى",
    "notes": "ملاحظات",
    "notesTooltip": "إضافة ملاحظات لهذا البيع (اختياري)",
    "subtotal": "المجموع الفرعي",
    "tax": "الضريبة",
    "total": "المجموع",
    "processSale": "معالجة البيع",
    "processing": "جاري المعالجة...",
    "quantity": "الكمية",
    "price": "السعر",
    "stock": "المخزون",
    "inStock": "متوفر",
    "remove": "إزالة",
    "productDetails": "تفاصيل المنتج",
    "sku": "رمز المنتج",
    "barcode": "الباركود",
    "notAvailable": "غير متوفر",
    "inventoryUpdated": "تم تحديث المخزون تلقائياً",
    "accountingEntriesCreated": "تم تسجيل القيود المحاسبية",
    "saleCompleted": "تم إتمام البيع بنجاح!",
    "error": "خطأ",
    "loadingProducts": "جاري تحميل المنتجات من قاعدة البيانات...",
    "errorLoadingProducts": "خطأ في تحميل المنتجات",
    "reload": "إعادة تحميل",
    "searchResults": "نتائج البحث:",
    "noProductsFound": "لم يتم العثور على منتجات",
    "clearSearch": "مسح البحث",
    "processingQRCode": "جاري معالجة بيانات رمز QR...",
    "scannerDetection": "اكتشاف الماسح",
    "scannerDetectionMessage": "قم بتوصيل ماسح الباركود USB وامسح منتجًا لتمكين الاكتشاف التلقائي.",
    "cameraPermission": "إذن الكاميرا",
    "allowCameraAccess": "يرجى السماح بالوصول إلى الكاميرا لمسح رموز QR",
    "scanningProduct": "جاري مسح المنتج...",
    "positionQRCode": "ضع رمز QR داخل الإطار",
    "productAdded": "تمت إضافة المنتج إلى السلة",
    "close": "إغلاق"
  },
  hi: { // Hindi
    "title": "पॉइंट ऑफ सेल सिस्टम",
    "searchProducts": "नाम, SKU या बारकोड द्वारा उत्पाद खोजें...",
    "scanProduct": "उत्पाद स्कैन करें",
    "addProduct": "उत्पाद जोड़ें",
    "clearCart": "कार्ट साफ़ करें",
    "emptyCart": "कार्ट में कोई आइटम नहीं",
    "customer": "ग्राहक",
    "walkInCustomer": "वॉक-इन ग्राहक",
    "selectCustomer": "इस बिक्री के लिए ग्राहक चुनें (वैकल्पिक)",
    "discount": "छूट",
    "applyDiscount": "उप-योग पर छूट लागू करें",
    "percentage": "प्रतिशत",
    "amount": "राशि",
    "taxRate": "कर दर (%)",
    "taxRateTooltip": "छूट के बाद उप-योग पर लागू कर दर",
    "paymentMethod": "भुगतान विधि",
    "paymentMethodTooltip": "भुगतान विधि चुनें",
    "cash": "नकद",
    "card": "कार्ड",
    "creditCard": "क्रेडिट कार्ड",
    "debitCard": "डेबिट कार्ड",
    "mobilePayment": "मोबाइल भुगतान",
    "other": "अन्य",
    "notes": "नोट्स",
    "notesTooltip": "इस बिक्री के लिए नोट्स जोड़ें (वैकल्पिक)",
    "subtotal": "उप-योग",
    "tax": "कर",
    "total": "कुल",
    "processSale": "बिक्री प्रक्रिया",
    "processing": "प्रसंस्करण...",
    "quantity": "मात्रा",
    "price": "मूल्य",
    "stock": "स्टॉक",
    "inStock": "स्टॉक में",
    "remove": "हटाएं",
    "productDetails": "उत्पाद विवरण",
    "sku": "SKU",
    "barcode": "बारकोड",
    "notAvailable": "उपलब्ध नहीं",
    "inventoryUpdated": "इन्वेंट्री स्वचालित रूप से अपडेट हुई",
    "accountingEntriesCreated": "लेखा प्रविष्टियाँ रिकॉर्ड की गईं",
    "saleCompleted": "बिक्री सफलतापूर्वक पूर्ण हुई!",
    "error": "त्रुटि",
    "loadingProducts": "डेटाबेस से उत्पाद लोड हो रहे हैं...",
    "errorLoadingProducts": "उत्पाद लोड करने में त्रुटि",
    "reload": "पुनः लोड करें",
    "searchResults": "खोज परिणाम:",
    "noProductsFound": "कोई उत्पाद नहीं मिला",
    "clearSearch": "खोज साफ़ करें",
    "processingQRCode": "QR कोड डेटा प्रसंस्करण...",
    "scannerDetection": "स्कैनर पहचान",
    "scannerDetectionMessage": "USB बारकोड स्कैनर कनेक्ट करें और स्वचालित पहचान सक्षम करने के लिए उत्पाद स्कैन करें।",
    "cameraPermission": "कैमरा अनुमति",
    "allowCameraAccess": "QR कोड स्कैन करने के लिए कृपया कैमरा एक्सेस की अनुमति दें",
    "scanningProduct": "उत्पाद स्कैन हो रहा है...",
    "positionQRCode": "QR कोड को फ्रेम के भीतर रखें",
    "productAdded": "उत्पाद कार्ट में जोड़ा गया",
    "close": "बंद करें"
  },
  id: { // Indonesian
    "title": "Sistem Point of Sale",
    "searchProducts": "Cari produk berdasarkan nama, SKU atau barcode...",
    "scanProduct": "Pindai Produk",
    "addProduct": "Tambah Produk",
    "clearCart": "Kosongkan Keranjang",
    "emptyCart": "Tidak ada item di keranjang",
    "customer": "Pelanggan",
    "walkInCustomer": "Pelanggan Langsung",
    "selectCustomer": "Pilih pelanggan untuk penjualan ini (opsional)",
    "discount": "Diskon",
    "applyDiscount": "Terapkan diskon ke subtotal",
    "percentage": "Persentase",
    "amount": "Jumlah",
    "taxRate": "Tarif Pajak (%)",
    "taxRateTooltip": "Tarif pajak diterapkan pada subtotal setelah diskon",
    "paymentMethod": "Metode Pembayaran",
    "paymentMethodTooltip": "Pilih metode pembayaran",
    "cash": "Tunai",
    "card": "Kartu",
    "creditCard": "Kartu Kredit",
    "debitCard": "Kartu Debit",
    "mobilePayment": "Pembayaran Mobile",
    "other": "Lainnya",
    "notes": "Catatan",
    "notesTooltip": "Tambahkan catatan untuk penjualan ini (opsional)",
    "subtotal": "Subtotal",
    "tax": "Pajak",
    "total": "Total",
    "processSale": "Proses Penjualan",
    "processing": "Memproses...",
    "quantity": "Jumlah",
    "price": "Harga",
    "stock": "Stok",
    "inStock": "tersedia",
    "remove": "Hapus",
    "productDetails": "Detail Produk",
    "sku": "SKU",
    "barcode": "Barcode",
    "notAvailable": "T/A",
    "inventoryUpdated": "Inventori diperbarui secara otomatis",
    "accountingEntriesCreated": "Entri akuntansi dicatat",
    "saleCompleted": "Penjualan berhasil diselesaikan!",
    "error": "Kesalahan",
    "loadingProducts": "Memuat produk dari database...",
    "errorLoadingProducts": "Kesalahan Memuat Produk",
    "reload": "Muat Ulang",
    "searchResults": "Hasil Pencarian:",
    "noProductsFound": "Tidak ada produk ditemukan",
    "clearSearch": "Hapus pencarian",
    "processingQRCode": "Memproses data kode QR...",
    "scannerDetection": "Deteksi Pemindai",
    "scannerDetectionMessage": "Hubungkan pemindai barcode USB dan pindai produk untuk mengaktifkan deteksi otomatis.",
    "cameraPermission": "Izin Kamera",
    "allowCameraAccess": "Harap izinkan akses kamera untuk memindai kode QR",
    "scanningProduct": "Memindai produk...",
    "positionQRCode": "Posisikan kode QR dalam bingkai",
    "productAdded": "Produk ditambahkan ke keranjang",
    "close": "Tutup"
  },
  nl: { // Dutch
    "title": "Kassasysteem",
    "searchProducts": "Zoek producten op naam, SKU of barcode...",
    "scanProduct": "Product Scannen",
    "addProduct": "Product Toevoegen",
    "clearCart": "Winkelwagen Legen",
    "emptyCart": "Geen items in winkelwagen",
    "customer": "Klant",
    "walkInCustomer": "Loopklant",
    "selectCustomer": "Selecteer klant voor deze verkoop (optioneel)",
    "discount": "Korting",
    "applyDiscount": "Korting toepassen op subtotaal",
    "percentage": "Percentage",
    "amount": "Bedrag",
    "taxRate": "Belastingtarief (%)",
    "taxRateTooltip": "Belastingtarief toegepast op subtotaal met korting",
    "paymentMethod": "Betaalmethode",
    "paymentMethodTooltip": "Selecteer betaalmethode",
    "cash": "Contant",
    "card": "Kaart",
    "creditCard": "Creditcard",
    "debitCard": "Betaalkaart",
    "mobilePayment": "Mobiele Betaling",
    "other": "Anders",
    "notes": "Notities",
    "notesTooltip": "Voeg notities toe voor deze verkoop (optioneel)",
    "subtotal": "Subtotaal",
    "tax": "Belasting",
    "total": "Totaal",
    "processSale": "Verkoop Verwerken",
    "processing": "Verwerken...",
    "quantity": "Aantal",
    "price": "Prijs",
    "stock": "Voorraad",
    "inStock": "op voorraad",
    "remove": "Verwijderen",
    "productDetails": "Productdetails",
    "sku": "SKU",
    "barcode": "Barcode",
    "notAvailable": "N.B.",
    "inventoryUpdated": "Inventaris automatisch bijgewerkt",
    "accountingEntriesCreated": "Boekhoudkundige boekingen geregistreerd",
    "saleCompleted": "Verkoop succesvol voltooid!",
    "error": "Fout",
    "loadingProducts": "Producten laden uit database...",
    "errorLoadingProducts": "Fout bij Laden Producten",
    "reload": "Herladen",
    "searchResults": "Zoekresultaten:",
    "noProductsFound": "Geen producten gevonden",
    "clearSearch": "Zoekopdracht wissen",
    "processingQRCode": "QR-code gegevens verwerken...",
    "scannerDetection": "Scanner Detectie",
    "scannerDetectionMessage": "Sluit een USB-barcodescanner aan en scan een product om automatische detectie in te schakelen.",
    "cameraPermission": "Camera Toestemming",
    "allowCameraAccess": "Geef toestemming voor cameratoegang om QR-codes te scannen",
    "scanningProduct": "Product scannen...",
    "positionQRCode": "Plaats de QR-code binnen het kader",
    "productAdded": "Product toegevoegd aan winkelwagen",
    "close": "Sluiten"
  },
  tr: { // Turkish
    "title": "Satış Noktası Sistemi",
    "searchProducts": "Ürünleri ad, SKU veya barkod ile arayın...",
    "scanProduct": "Ürün Tara",
    "addProduct": "Ürün Ekle",
    "clearCart": "Sepeti Temizle",
    "emptyCart": "Sepette ürün yok",
    "customer": "Müşteri",
    "walkInCustomer": "Gelen Müşteri",
    "selectCustomer": "Bu satış için müşteri seçin (isteğe bağlı)",
    "discount": "İndirim",
    "applyDiscount": "Ara toplama indirim uygula",
    "percentage": "Yüzde",
    "amount": "Tutar",
    "taxRate": "Vergi Oranı (%)",
    "taxRateTooltip": "İndirimli ara toplama uygulanan vergi oranı",
    "paymentMethod": "Ödeme Yöntemi",
    "paymentMethodTooltip": "Ödeme yöntemi seçin",
    "cash": "Nakit",
    "card": "Kart",
    "creditCard": "Kredi Kartı",
    "debitCard": "Banka Kartı",
    "mobilePayment": "Mobil Ödeme",
    "other": "Diğer",
    "notes": "Notlar",
    "notesTooltip": "Bu satış için not ekleyin (isteğe bağlı)",
    "subtotal": "Ara Toplam",
    "tax": "Vergi",
    "total": "Toplam",
    "processSale": "Satışı İşle",
    "processing": "İşleniyor...",
    "quantity": "Miktar",
    "price": "Fiyat",
    "stock": "Stok",
    "inStock": "stokta",
    "remove": "Kaldır",
    "productDetails": "Ürün Detayları",
    "sku": "SKU",
    "barcode": "Barkod",
    "notAvailable": "Mevcut Değil",
    "inventoryUpdated": "Envanter otomatik olarak güncellendi",
    "accountingEntriesCreated": "Muhasebe kayıtları oluşturuldu",
    "saleCompleted": "Satış başarıyla tamamlandı!",
    "error": "Hata",
    "loadingProducts": "Ürünler veritabanından yükleniyor...",
    "errorLoadingProducts": "Ürün Yükleme Hatası",
    "reload": "Yeniden Yükle",
    "searchResults": "Arama Sonuçları:",
    "noProductsFound": "Ürün bulunamadı",
    "clearSearch": "Aramayı temizle",
    "processingQRCode": "QR kod verileri işleniyor...",
    "scannerDetection": "Tarayıcı Algılama",
    "scannerDetectionMessage": "Otomatik algılamayı etkinleştirmek için USB barkod tarayıcısını bağlayın ve bir ürün tarayın.",
    "cameraPermission": "Kamera İzni",
    "allowCameraAccess": "QR kodları taramak için lütfen kamera erişimine izin verin",
    "scanningProduct": "Ürün taranıyor...",
    "positionQRCode": "QR kodunu çerçeve içine yerleştirin",
    "productAdded": "Ürün sepete eklendi",
    "close": "Kapat"
  },
  vi: { // Vietnamese
    "title": "Hệ Thống Bán Hàng",
    "searchProducts": "Tìm sản phẩm theo tên, mã SKU hoặc mã vạch...",
    "scanProduct": "Quét Sản Phẩm",
    "addProduct": "Thêm Sản Phẩm",
    "clearCart": "Xóa Giỏ Hàng",
    "emptyCart": "Không có sản phẩm trong giỏ",
    "customer": "Khách Hàng",
    "walkInCustomer": "Khách Vãng Lai",
    "selectCustomer": "Chọn khách hàng cho giao dịch này (tùy chọn)",
    "discount": "Giảm Giá",
    "applyDiscount": "Áp dụng giảm giá cho tổng phụ",
    "percentage": "Phần Trăm",
    "amount": "Số Tiền",
    "taxRate": "Thuế Suất (%)",
    "taxRateTooltip": "Thuế suất áp dụng cho tổng phụ sau giảm giá",
    "paymentMethod": "Phương Thức Thanh Toán",
    "paymentMethodTooltip": "Chọn phương thức thanh toán",
    "cash": "Tiền Mặt",
    "card": "Thẻ",
    "creditCard": "Thẻ Tín Dụng",
    "debitCard": "Thẻ Ghi Nợ",
    "mobilePayment": "Thanh Toán Di Động",
    "other": "Khác",
    "notes": "Ghi Chú",
    "notesTooltip": "Thêm ghi chú cho giao dịch này (tùy chọn)",
    "subtotal": "Tổng Phụ",
    "tax": "Thuế",
    "total": "Tổng Cộng",
    "processSale": "Xử Lý Bán Hàng",
    "processing": "Đang xử lý...",
    "quantity": "Số Lượng",
    "price": "Giá",
    "stock": "Kho",
    "inStock": "còn hàng",
    "remove": "Xóa",
    "productDetails": "Chi Tiết Sản Phẩm",
    "sku": "Mã SKU",
    "barcode": "Mã Vạch",
    "notAvailable": "Không có",
    "inventoryUpdated": "Kho hàng đã được cập nhật tự động",
    "accountingEntriesCreated": "Bút toán kế toán đã được ghi nhận",
    "saleCompleted": "Bán hàng thành công!",
    "error": "Lỗi",
    "loadingProducts": "Đang tải sản phẩm từ cơ sở dữ liệu...",
    "errorLoadingProducts": "Lỗi Tải Sản Phẩm",
    "reload": "Tải Lại",
    "searchResults": "Kết Quả Tìm Kiếm:",
    "noProductsFound": "Không tìm thấy sản phẩm",
    "clearSearch": "Xóa tìm kiếm",
    "processingQRCode": "Đang xử lý dữ liệu mã QR...",
    "scannerDetection": "Phát Hiện Máy Quét",
    "scannerDetectionMessage": "Kết nối máy quét mã vạch USB và quét sản phẩm để kích hoạt phát hiện tự động.",
    "cameraPermission": "Quyền Camera",
    "allowCameraAccess": "Vui lòng cho phép truy cập camera để quét mã QR",
    "scanningProduct": "Đang quét sản phẩm...",
    "positionQRCode": "Đặt mã QR trong khung",
    "productAdded": "Sản phẩm đã được thêm vào giỏ",
    "close": "Đóng"
  },
  // African languages
  sw: { // Swahili
    "title": "Mfumo wa Mahali pa Kuuza",
    "searchProducts": "Tafuta bidhaa kwa jina, SKU au barcode...",
    "scanProduct": "Changanua Bidhaa",
    "addProduct": "Ongeza Bidhaa",
    "clearCart": "Futa Kikapu",
    "emptyCart": "Hakuna bidhaa kwenye kikapu",
    "customer": "Mteja",
    "walkInCustomer": "Mteja wa Kupita",
    "selectCustomer": "Chagua mteja kwa mauzo haya (si lazima)",
    "discount": "Punguzo",
    "applyDiscount": "Tumia punguzo kwa jumla ndogo",
    "percentage": "Asilimia",
    "amount": "Kiasi",
    "taxRate": "Kiwango cha Kodi (%)",
    "taxRateTooltip": "Kiwango cha kodi kinachotumika kwa jumla ndogo baada ya punguzo",
    "paymentMethod": "Njia ya Malipo",
    "paymentMethodTooltip": "Chagua njia ya malipo",
    "cash": "Taslimu",
    "card": "Kadi",
    "creditCard": "Kadi ya Mkopo",
    "debitCard": "Kadi ya Benki",
    "mobilePayment": "Malipo ya Simu",
    "other": "Nyingine",
    "notes": "Maelezo",
    "notesTooltip": "Ongeza maelezo kwa mauzo haya (si lazima)",
    "subtotal": "Jumla Ndogo",
    "tax": "Kodi",
    "total": "Jumla",
    "processSale": "Shughulikia Mauzo",
    "processing": "Inashughulikia...",
    "quantity": "Idadi",
    "price": "Bei",
    "stock": "Hisa",
    "inStock": "ipo",
    "remove": "Ondoa",
    "productDetails": "Maelezo ya Bidhaa",
    "sku": "SKU",
    "barcode": "Barcode",
    "notAvailable": "Haipatikani",
    "inventoryUpdated": "Orodha ya bidhaa imesasishwa kiotomatiki",
    "accountingEntriesCreated": "Maingizo ya uhasibu yameandikwa",
    "saleCompleted": "Mauzo yamekamilika kwa mafanikio!",
    "error": "Kosa",
    "loadingProducts": "Inapakia bidhaa kutoka hifadhidata...",
    "errorLoadingProducts": "Kosa la Kupakia Bidhaa",
    "reload": "Pakia Tena",
    "searchResults": "Matokeo ya Utafutaji:",
    "noProductsFound": "Hakuna bidhaa zilizopatikana",
    "clearSearch": "Futa utafutaji",
    "processingQRCode": "Inachakata data ya msimbo wa QR...",
    "scannerDetection": "Utambuzi wa Kichunguzi",
    "scannerDetectionMessage": "Unganisha kichunguzi cha barcode cha USB na chunguza bidhaa ili kuwezesha utambuzi wa kiotomatiki.",
    "cameraPermission": "Ruhusa ya Kamera",
    "allowCameraAccess": "Tafadhali ruhusu ufikiaji wa kamera ili kuchunguza misimbo ya QR",
    "scanningProduct": "Inachunguza bidhaa...",
    "positionQRCode": "Weka msimbo wa QR ndani ya fremu",
    "productAdded": "Bidhaa imeongezwa kwenye kikapu",
    "close": "Funga"
  },
  ha: { // Hausa
    "title": "Tsarin Wurin Siyarwa",
    "searchProducts": "Nemo kayayyaki ta suna, SKU ko lambar kodi...",
    "scanProduct": "Duba Kayayyaki",
    "addProduct": "Ƙara Kayayyaki",
    "clearCart": "Share Kwando",
    "emptyCart": "Babu kaya a cikin kwando",
    "customer": "Abokin Ciniki",
    "walkInCustomer": "Abokin Ciniki mai Wucewa",
    "selectCustomer": "Zaɓi abokin ciniki don wannan siyarwa (ba dole ba)",
    "discount": "Rangwame",
    "applyDiscount": "Yi amfani da rangwame ga ƙaramin jimla",
    "percentage": "Kashi",
    "amount": "Adadi",
    "taxRate": "Yawan Haraji (%)",
    "taxRateTooltip": "Yawan haraji da ake amfani da shi ga ƙaramin jimla bayan rangwame",
    "paymentMethod": "Hanyar Biyan Kuɗi",
    "paymentMethodTooltip": "Zaɓi hanyar biyan kuɗi",
    "cash": "Tsabar Kuɗi",
    "card": "Kati",
    "creditCard": "Katin Bashi",
    "debitCard": "Katin Banki",
    "mobilePayment": "Biyan Kuɗi ta Wayar Hannu",
    "other": "Wani",
    "notes": "Bayanan Kula",
    "notesTooltip": "Ƙara bayanan kula don wannan siyarwa (ba dole ba)",
    "subtotal": "Ƙaramin Jimla",
    "tax": "Haraji",
    "total": "Jimla",
    "processSale": "Aiwatar da Siyarwa",
    "processing": "Ana aiwatarwa...",
    "quantity": "Yawa",
    "price": "Farashi",
    "stock": "Ajiya",
    "inStock": "akwai",
    "remove": "Cire",
    "productDetails": "Bayanan Kayayyaki",
    "sku": "SKU",
    "barcode": "Lambar Kodi",
    "notAvailable": "Babu",
    "inventoryUpdated": "An sabunta kayayyaki ta atomatik",
    "accountingEntriesCreated": "An yi rikodin bayanan lissafi",
    "saleCompleted": "An kammala siyarwa cikin nasara!",
    "error": "Kuskure",
    "loadingProducts": "Ana loda kayayyaki daga bayanai...",
    "errorLoadingProducts": "Kuskuren Loda Kayayyaki",
    "reload": "Sake Loda",
    "searchResults": "Sakamakon Bincike:",
    "noProductsFound": "Ba a sami kayayyaki ba",
    "clearSearch": "Share bincike",
    "processingQRCode": "Ana aiwatar da bayanan lambar QR...",
    "scannerDetection": "Gano Na'urar Dubawa",
    "scannerDetectionMessage": "Haɗa na'urar duba lambar kodi ta USB kuma duba kayayyaki don kunna ganowa ta atomatik.",
    "cameraPermission": "Izinin Kyamara",
    "allowCameraAccess": "Don Allah ka ba da izinin kyamara don duba lambobin QR",
    "scanningProduct": "Ana duba kayayyaki...",
    "positionQRCode": "Sanya lambar QR a cikin firam",
    "productAdded": "An ƙara kayayyaki zuwa kwando",
    "close": "Rufe"
  },
  am: { // Amharic
    "title": "የሽያጭ ቦታ ስርዓት",
    "searchProducts": "ምርቶችን በስም፣ SKU ወይም ባርኮድ ይፈልጉ...",
    "scanProduct": "ምርት ስካን ያድርጉ",
    "addProduct": "ምርት ይጨምሩ",
    "clearCart": "ጋሪን ያጸዱ",
    "emptyCart": "በጋሪ ውስጥ ምንም እቃዎች የሉም",
    "customer": "ደንበኛ",
    "walkInCustomer": "የገባ ደንበኛ",
    "selectCustomer": "ለዚህ ሽያጭ ደንበኛ ይምረጡ (አማራጭ)",
    "discount": "ቅናሽ",
    "applyDiscount": "ለንዑስ ድምር ቅናሽ ይተግብሩ",
    "percentage": "መቶኛ",
    "amount": "መጠን",
    "taxRate": "የግብር መጠን (%)",
    "taxRateTooltip": "ከቅናሽ በኋላ ለንዑስ ድምር የሚተገበር የግብር መጠን",
    "paymentMethod": "የክፍያ ዘዴ",
    "paymentMethodTooltip": "የክፍያ ዘዴ ይምረጡ",
    "cash": "ጥሬ ገንዘብ",
    "card": "ካርድ",
    "creditCard": "የክሬዲት ካርድ",
    "debitCard": "የዴቢት ካርድ",
    "mobilePayment": "የሞባይል ክፍያ",
    "other": "ሌላ",
    "notes": "ማስታወሻዎች",
    "notesTooltip": "ለዚህ ሽያጭ ማስታወሻዎችን ይጨምሩ (አማራጭ)",
    "subtotal": "ንዑስ ድምር",
    "tax": "ግብር",
    "total": "ጠቅላላ",
    "processSale": "ሽያጭን ያስኬዱ",
    "processing": "እየተስተናገደ ነው...",
    "quantity": "ብዛት",
    "price": "ዋጋ",
    "stock": "ክምችት",
    "inStock": "በክምችት",
    "remove": "አስወግድ",
    "productDetails": "የምርት ዝርዝሮች",
    "sku": "SKU",
    "barcode": "ባርኮድ",
    "notAvailable": "የለም",
    "inventoryUpdated": "ክምችት በራስ-ሰር ተዘምኗል",
    "accountingEntriesCreated": "የሂሳብ መዝገቦች ተመዝግበዋል",
    "saleCompleted": "ሽያጭ በተሳካ ሁኔታ ተጠናቋል!",
    "error": "ስህተት",
    "loadingProducts": "ምርቶችን ከመረጃ ቋት እየጫኑ ነው...",
    "errorLoadingProducts": "ምርቶችን የመጫን ስህተት",
    "reload": "እንደገና ጫን",
    "searchResults": "የፍለጋ ውጤቶች:",
    "noProductsFound": "ምንም ምርቶች አልተገኙም",
    "clearSearch": "ፍለጋን ያጸዱ",
    "processingQRCode": "የQR ኮድ ውሂብን በማስኬድ ላይ...",
    "scannerDetection": "ስካነር ማወቅ",
    "scannerDetectionMessage": "ራስ-ሰር ማወቅን ለማንቃት የUSB ባርኮድ ስካነር ያገናኙ እና ምርት ይቃኙ።",
    "cameraPermission": "የካሜራ ፍቃድ",
    "allowCameraAccess": "QR ኮዶችን ለመቃኘት እባክዎ የካሜራ መዳረሻን ይፍቀዱ",
    "scanningProduct": "ምርት በመቃኘት ላይ...",
    "positionQRCode": "QR ኮድን በክፈፉ ውስጥ ያስቀምጡ",
    "productAdded": "ምርት ወደ ጋሪ ተጨምሯል",
    "close": "ዝጋ"
  },
  yo: { // Yoruba
    "title": "Eto Ibi Tita",
    "searchProducts": "Wa awọn ọja pẹlu orukọ, SKU tabi koodu ila...",
    "scanProduct": "Ṣayẹwo Ọja",
    "addProduct": "Fi Ọja Kun",
    "clearCart": "Pa Kẹkẹ Rẹ",
    "emptyCart": "Ko si ohun kankan ninu kẹkẹ",
    "customer": "Alabara",
    "walkInCustomer": "Alabara Ti o Wọle",
    "selectCustomer": "Yan alabara fun tita yii (iyan)",
    "discount": "Ẹdinwo",
    "applyDiscount": "Lo ẹdinwo si apao kekere",
    "percentage": "Ogorun",
    "amount": "Iye",
    "taxRate": "Oṣuwọn Owo-ori (%)",
    "taxRateTooltip": "Oṣuwọn owo-ori ti a lo si apao kekere pẹlu ẹdinwo",
    "paymentMethod": "Ọna Isanwo",
    "paymentMethodTooltip": "Yan ọna isanwo",
    "cash": "Owo",
    "card": "Kaadi",
    "creditCard": "Kaadi Gbese",
    "debitCard": "Kaadi Banki",
    "mobilePayment": "Isanwo Foonu",
    "other": "Miiran",
    "notes": "Awọn Akọsilẹ",
    "notesTooltip": "Fi awọn akọsilẹ kun fun tita yii (iyan)",
    "subtotal": "Apao Kekere",
    "tax": "Owo-ori",
    "total": "Apapọ",
    "processSale": "Ṣe Tita",
    "processing": "N ṣiṣẹ...",
    "quantity": "Iye",
    "price": "Owo",
    "stock": "Iṣura",
    "inStock": "wa ninu iṣura",
    "remove": "Yọkuro",
    "productDetails": "Awọn Alaye Ọja",
    "sku": "SKU",
    "barcode": "Koodu Ila",
    "notAvailable": "Ko Si",
    "inventoryUpdated": "Iṣura ti ni imudojuiwọn laifọwọyi",
    "accountingEntriesCreated": "Awọn iforukọsilẹ iṣiro ti wa ni kikọ",
    "saleCompleted": "Tita ti pari ni aṣeyọri!",
    "error": "Aṣiṣe",
    "loadingProducts": "N gbe awọn ọja jade lati data...",
    "errorLoadingProducts": "Aṣiṣe Gbigbe Awọn Ọja",
    "reload": "Tun Gbe Jade",
    "searchResults": "Awọn Esi Wiwa:",
    "noProductsFound": "Ko ri awọn ọja kankan",
    "clearSearch": "Pa wiwa rẹ",
    "processingQRCode": "N ṣe data koodu QR...",
    "scannerDetection": "Wiwa Ẹrọ Ayẹwo",
    "scannerDetectionMessage": "So ẹrọ ayẹwo koodu ila USB mọ ki o si yẹ ọja wo lati mu wiwa laifọwọyi ṣiṣẹ.",
    "cameraPermission": "Igbanilaaye Kamẹra",
    "allowCameraAccess": "Jọwọ gba laaye lati lo kamẹra lati yẹ awọn koodu QR wo",
    "scanningProduct": "N yẹ ọja wo...",
    "positionQRCode": "Fi koodu QR sinu fireemu",
    "productAdded": "Ọja ti fi si kẹkẹ",
    "close": "Pade"
  },
  zu: { // Zulu
    "title": "Uhlelo Lwendawo Yokuthengisa",
    "searchProducts": "Sesha imikhiqizo ngegama, i-SKU noma ibhakhodi...",
    "scanProduct": "Skena Umkhiqizo",
    "addProduct": "Engeza Umkhiqizo",
    "clearCart": "Sula Ikalishi",
    "emptyCart": "Ayikho imikhiqizo ekalishini",
    "customer": "Ikhasimende",
    "walkInCustomer": "Ikhasimende Elingena nje",
    "selectCustomer": "Khetha ikhasimende lalokhu kuthengisa (akuphoqelekile)",
    "discount": "Isaphulelo",
    "applyDiscount": "Sebenzisa isaphulelo esambeni esincane",
    "percentage": "Iphesenti",
    "amount": "Inani",
    "taxRate": "Izinga Lentela (%)",
    "taxRateTooltip": "Izinga lentela elisetshenziswa esambeni esincane ngemva kwesaphulelo",
    "paymentMethod": "Indlela Yokukhokha",
    "paymentMethodTooltip": "Khetha indlela yokukhokha",
    "cash": "Imali",
    "card": "Ikhadi",
    "creditCard": "Ikhadi Lesikweletu",
    "debitCard": "Ikhadi Lebhange",
    "mobilePayment": "Inkokhelo Yeselula",
    "other": "Okunye",
    "notes": "Amanothi",
    "notesTooltip": "Engeza amanothi kulokhu kuthengisa (akuphoqelekile)",
    "subtotal": "Isamba Esincane",
    "tax": "Intela",
    "total": "Isamba",
    "processSale": "Qhuba Ukuthengisa",
    "processing": "Iyasebenza...",
    "quantity": "Inani",
    "price": "Intengo",
    "stock": "Isitoko",
    "inStock": "sikhona",
    "remove": "Susa",
    "productDetails": "Imininingwane Yomkhiqizo",
    "sku": "I-SKU",
    "barcode": "Ibhakhodi",
    "notAvailable": "Ayitholakali",
    "inventoryUpdated": "Uhlu lwempahla lubuyekeziwe ngokuzenzakalelayo",
    "accountingEntriesCreated": "Okufakiwe kwezimali kurekhodiwe",
    "saleCompleted": "Ukuthengisa kuqediwe ngempumelelo!",
    "error": "Iphutha",
    "loadingProducts": "Ilayisha imikhiqizo kusuka kudathabheyisi...",
    "errorLoadingProducts": "Iphutha Lokulayisha Imikhiqizo",
    "reload": "Layisha Kabusha",
    "searchResults": "Imiphumela Yosesho:",
    "noProductsFound": "Ayikho imikhiqizo etholiwe",
    "clearSearch": "Sula usesho",
    "processingQRCode": "Icubungula idatha yekhodi ye-QR...",
    "scannerDetection": "Ukutholwa Kwesikena",
    "scannerDetectionMessage": "Xhuma isikena sebhakhodi ye-USB bese uskena umkhiqizo ukuze unike amandla ukutholwa okuzenzakalelayo.",
    "cameraPermission": "Imvume Yekhamera",
    "allowCameraAccess": "Sicela uvumele ukufinyelela kwekhamera ukuze uskene amakhodi e-QR",
    "scanningProduct": "Iskena umkhiqizo...",
    "positionQRCode": "Beka ikhodi ye-QR ngaphakathi kohlaka",
    "productAdded": "Umkhiqizo ungezwe ekalishini",
    "close": "Vala"
  }
};

// Generate translation files for each language
Object.keys(translations).forEach(lang => {
  const filePath = path.join(__dirname, '..', 'public', 'locales', lang, 'pos.json');
  fs.writeFileSync(filePath, JSON.stringify(translations[lang], null, 2), 'utf8');
  console.log(`Created ${lang}/pos.json`);
});

console.log('\n✅ POS translations created for all 20 languages!');