# Generated by Django 5.1.7 on 2025-04-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('setup_status', models.CharField(default='not_started', max_length=20)),
                ('setup_error', models.TextField(blank=True, null=True)),
                ('setup_started_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'db_table': 'onboarding_userprofile',
            },
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='current_step',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business_info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='business_info', max_length=50),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business_info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='business_info', max_length=50),
        ),
    ]
