# Generated by Django 5.0.6 on 2025-02-21 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0003_initial'),
        ('business', '0002_initial'),
        ('finance', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='purchases.bill'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.accountreconciliation'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_account', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='finance.financialstatement'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='intercompanyaccount',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='intercompanyaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intercompany_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intercompanytransaction',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_intercompany_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intercompanytransaction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='intercompanytransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intercompany_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intercompanytransaction',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_intercompany_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='monthendclosing',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthendclosing',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='monthendclosing',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthendclosing',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthendtask',
            name='closing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='finance.monthendclosing'),
        ),
        migrations.AddField(
            model_name='monthendtask',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='bank_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banktransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='finance_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='matched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.accountreconciliation'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_accounts', to='finance.accounttype'),
        ),
        migrations.AddField(
            model_name='revenueaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_account', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='salestaxaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_account', to='finance.financetransaction'),
        ),
        migrations.AddIndex(
            model_name='accountreconciliation',
            index=models.Index(fields=['reconciliation_date'], name='finance_acc_reconci_42d939_idx'),
        ),
        migrations.AddIndex(
            model_name='accountreconciliation',
            index=models.Index(fields=['status'], name='finance_acc_status_09fb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountreconciliation',
            index=models.Index(fields=['business'], name='finance_acc_busines_2d55e9_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='finance_acc_account_932be5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['business', 'account_type'], name='finance_acc_busines_ce3709_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status'], name='finance_acc_status_902c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['date_time'], name='finance_aud_date_ti_1fbc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['transaction_type'], name='finance_aud_transac_e8247f_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['business'], name='finance_aud_busines_2dc5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user'], name='finance_aud_user_id_d1b6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status'], name='finance_bud_status_adfa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['business', 'fiscal_year'], name='finance_bud_busines_276cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['category'], name='finance_bud_categor_5f83b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('business', 'name', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['item_type'], name='finance_bud_item_ty_1e019f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['account'], name='finance_bud_account_63bc37_idx'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['code'], name='finance_cos_code_343da6_idx'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['business'], name='finance_cos_busines_6f213c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcategory',
            unique_together={('business', 'code')},
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['status'], name='finance_cos_status_8bb3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['date'], name='finance_cos_date_44c6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='costentry',
            index=models.Index(fields=['business', 'category'], name='finance_cos_busines_c0eff2_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocation',
            index=models.Index(fields=['status'], name='finance_cos_status_4c1ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocation',
            index=models.Index(fields=['department', 'cost_center'], name='finance_cos_departm_686784_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['transaction_id'], name='finance_fin_transac_f0448d_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['date'], name='finance_fin_date_4c2559_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['status'], name='finance_fin_status_e942fc_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['category'], name='finance_fin_categor_cc74a8_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['business'], name='finance_fin_busines_17c25b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['statement_type'], name='finance_fin_stateme_9dc46c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['status'], name='finance_fin_status_9b4347_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['business', 'fiscal_year'], name='finance_fin_busines_06d07d_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['start_date', 'end_date'], name='finance_fin_start_d_16cffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('business', 'statement_type', 'start_date', 'end_date', 'version')},
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['asset_tag'], name='finance_fix_asset_t_3b3c49_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status'], name='finance_fix_status_99b229_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['business', 'asset_type'], name='finance_fix_busines_f909bd_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanyaccount',
            index=models.Index(fields=['status'], name='finance_int_status_e8c61a_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanyaccount',
            index=models.Index(fields=['business', 'entity'], name='finance_int_busines_804950_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanyaccount',
            index=models.Index(fields=['account_type'], name='finance_int_account_7a5093_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intercompanyaccount',
            unique_together={('business', 'entity', 'account_type')},
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['status'], name='finance_int_status_ef24ec_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['date'], name='finance_int_date_e7199e_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['business', 'transaction_type'], name='finance_int_busines_19133b_idx'),
        ),
        migrations.AddIndex(
            model_name='intercompanytransaction',
            index=models.Index(fields=['entity_from', 'entity_to'], name='finance_int_entity__fa76be_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='finance_jou_date_35a9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='finance_jou_status_d9feb8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['business'], name='finance_jou_busines_031c71_idx'),
        ),
        migrations.AddIndex(
            model_name='monthendclosing',
            index=models.Index(fields=['status'], name='finance_mon_status_a768ab_idx'),
        ),
        migrations.AddIndex(
            model_name='monthendclosing',
            index=models.Index(fields=['business', 'year', 'month'], name='finance_mon_busines_645c51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthendclosing',
            unique_together={('month', 'year', 'business')},
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['match_status'], name='finance_rec_match_s_a1868c_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['matched_at'], name='finance_rec_matched_171690_idx'),
        ),
    ]
