# Generated by Django 5.0.6 on 2024-09-05 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_initial'),
        ('finance', '0001_initial'),
        ('purchases', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='finance.account'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.accountcategory'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='costentry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcategory'),
        ),
        migrations.AddField(
            model_name='costallocation',
            name='cost_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.costentry'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='purchases.bill'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_account', to='finance.financetransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('statement_type', 'date')},
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AlterUniqueTogether(
            name='monthendclosing',
            unique_together={('month', 'year')},
        ),
        migrations.AddField(
            model_name='monthendtask',
            name='closing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='finance.monthendclosing'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='bank_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banktransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='finance_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.accountreconciliation'),
        ),
        migrations.AddField(
            model_name='revenueaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_accounts', to='finance.accounttype'),
        ),
        migrations.AddField(
            model_name='revenueaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_account', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='salestaxaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_account', to='finance.financetransaction'),
        ),
    ]
