# Generated by Django 5.0.6 on 2024-08-31 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('finance', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_account', to='finance.financetransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('statement_type', 'date')},
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AlterUniqueTogether(
            name='monthendclosing',
            unique_together={('month', 'year')},
        ),
        migrations.AddField(
            model_name='monthendtask',
            name='closing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='finance.monthendclosing'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='bank_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banktransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='finance_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.accountreconciliation'),
        ),
        migrations.AddField(
            model_name='revenueaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_accounts', to='finance.accounttype'),
        ),
        migrations.AddField(
            model_name='revenueaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_account', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='salestaxaccount',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_account', to='finance.financetransaction'),
        ),
    ]
