# Generated by Django 5.0.6 on 2024-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='account_type_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
