# Generated by Django 5.0.6 on 2024-08-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('Current Asset', 'Current Asset'), ('Current Liability', 'Current Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Operating Expense', 'Operating Expense'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Non-Operating Expense', 'Non-Operating Expense')], max_length=100),
        ),
    ]
