# Generated by Django 5.0.6 on 2024-08-31 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('depreciation_method', models.CharField(choices=[('SL', 'Straight Line'), ('DB', 'Declining Balance'), ('SYD', 'Sum of Years Digits'), ('UOP', 'Units of Production')], max_length=3)),
                ('useful_life', models.PositiveIntegerField(help_text='Useful life in years')),
                ('salvage_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
