# Generated by Django 5.0.6 on 2024-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_accounttype_account_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
