# Generated by Django 5.0.6 on 2024-09-01 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_budget_budgetitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntercompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('loan', 'Loan')], max_length=20)),
                ('entity', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='IntercompanyTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('loan', 'Loan'), ('asset_transfer', 'Asset Transfer'), ('service', 'Service'), ('cost_allocation', 'Cost Allocation')], max_length=20)),
                ('entity_from', models.CharField(max_length=100)),
                ('entity_to', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField()),
                ('document_reference', models.CharField(blank=True, max_length=50)),
                ('reconciliation_status', models.CharField(default='unmatched', max_length=20)),
                ('transfer_pricing', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('modify', 'Modify'), ('delete', 'Delete'), ('approve', 'Approve')], max_length=10)),
                ('transaction_id', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('affected_accounts', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('module', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('cost_type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], max_length=10)),
                ('cost_nature', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('project', models.CharField(blank=True, max_length=100)),
                ('cost_driver', models.CharField(blank=True, max_length=100)),
                ('job_process_id', models.CharField(blank=True, max_length=50)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_base', models.CharField(max_length=100)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.costentry')),
            ],
        ),
    ]
