# Generated by Django 5.0.6 on 2024-06-21 00:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_created_at_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTaxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_account', to='finance.transaction')),
            ],
        ),
    ]
