# Generated by Django 5.0.6 on 2024-06-21 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_salestaxaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestaxaccount',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestaxaccount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
