# Generated by Django 5.0.6 on 2024-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
