# Generated by Django 5.2.5 on 2025-08-31 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_order_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new message types for calling
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('text', 'Text Message'),
                    ('image', 'Image'),
                    ('voice', 'Voice Note'),
                    ('voice_call', 'Voice Call'),
                    ('video_call', 'Video Call'),
                    ('order_request', 'Order Request'),
                    ('order_confirmation', 'Order Confirmation'),
                    ('system', 'System Message'),
                ],
                default='text',
                max_length=20
            ),
        ),
        # Add call-related fields to ChatMessage
        migrations.AddField(
            model_name='chatmessage',
            name='call_duration',
            field=models.IntegerField(
                blank=True,
                help_text='Call duration in seconds',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='call_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('initiated', 'Call Initiated'),
                    ('ringing', 'Ringing'),
                    ('answered', 'Answered'),
                    ('completed', 'Completed'),
                    ('missed', 'Missed'),
                    ('declined', 'Declined'),
                    ('failed', 'Failed'),
                    ('busy', 'Busy'),
                ],
                help_text='Status of the call',
                max_length=15,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='call_session_id',
            field=models.CharField(
                blank=True,
                help_text='WebRTC session identifier',
                max_length=100,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='call_started_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the call was started',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='call_ended_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the call ended',
                null=True
            ),
        ),
        # Create CallSession model
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique WebRTC session identifier', max_length=100, unique=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice Call'), ('video', 'Video Call')], help_text='Type of call', max_length=10)),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('ringing', 'Ringing'), ('connecting', 'Connecting'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], default='initiating', help_text='Current session status', max_length=15)),
                ('ice_servers', models.JSONField(default=list, help_text='ICE servers configuration for WebRTC')),
                ('offer_sdp', models.TextField(blank=True, help_text='WebRTC offer SDP from caller', null=True)),
                ('answer_sdp', models.TextField(blank=True, help_text='WebRTC answer SDP from callee', null=True)),
                ('ice_candidates', models.JSONField(default=list, help_text='ICE candidates exchange')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='Associated chat conversation', on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='chat.chatconversation')),
                ('call_message', models.OneToOneField(blank=True, help_text='Associated call message in chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='chat.chatmessage')),
                ('caller', models.ForeignKey(help_text='User who initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('callee', models.ForeignKey(help_text='User receiving the call', on_delete=django.db.models.deletion.CASCADE, related_name='received_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_sessions',
                'ordering': ['-created_at'],
            },
        ),
        # Add indexes for CallSession
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['session_id'], name='chat_callsession_session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller', 'created_at'], name='chat_callsession_caller_created_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['callee', 'created_at'], name='chat_callsession_callee_created_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status'], name='chat_callsession_status_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation'], name='chat_callsession_conversation_idx'),
        ),
    ]
