///Users/kuoldeng/projectx/frontend/pyfactor_next/src/app/utils/businessData.js
export const businessTypes = [
    "Accounting and Bookkeeping",
    "Administration and Office Services",
    "Adventure Tourism and Tour Guides",
    "Advertising and Marketing",
    "Agribusiness and Agricultural Consulting",
    "Agricultural Machinery",
    "Agriculture and Farming",
    "Air Conditioning and HVAC Services",
    "AI, Machine Learning, and Data Science Services",
    "Animal and Pet Services",
    "Apparel and Clothing",
    "Architecture and Design",
    "Arts and Crafts",
    "Automotive, Leasing, and Repair",
    "Babysitting and Childcare Services",
    "Banking and Finance",
    "Barbershops, Hair Salons, and Beauty Services",
    "Beverage and Food Services",
    "Biotechnology and Pharmaceuticals",
    "Blockchain, Cryptocurrencies, and Exchanges",
    "Broadcasting, Media, and Video Streaming",
    "Business Consulting and Advisory Services",
    "Catering and Food Trucks",
    "Cleaning Services",
    "Cloud Computing and IT Services",
    "Construction and Contracting",
    "Craft Beverages (Breweries, Distilleries)",
    "Creative Services (Design, Graphic Design)",
    "Cultural Heritage and Preservation",
    "Cybersecurity and Risk Management",
    "Data Analysis and Business Intelligence",
    "Dairy and Livestock Farming",
    "Digital Marketing and Online Services",
    "DJ, Music, and Entertainment Services",
    "Distribution, Freight Forwarding, and Logistics",
    "Drone and Aerial Services",
    "E-commerce and Retail",
    "Education and Tutoring",
    "Electronics and IT Equipment",
    "Energy Auditing and Sustainability Consulting",
    "Engineering and Technical Services",
    "Event Planning, Rentals, and Technology",
    "Export and Import Trade",
    "Fashion and Apparel",
    "Film, Television, and Media Production",
    "Financial Planning and Investment Services",
    "Fishing and Aquaculture",
    "Fitness and Personal Training",
    "Floristry and Gardening",
    "Forestry and Natural Resource Management",
    "Franchising and Licensing",
    "Freelance Platforms and Gig Economy",
    "Fundraising and Non-Profit Services",
    "Furniture and Home Decor",
    "Green Building, Renewable Energy, and Solar",
    "Healthcare and Medical Services",
    "Home Improvement and Renovation",
    "Hospitality, Hotels, and Vacation Rentals",
    "Human Resources and Recruitment",
    "Hydroelectric and Wind Energy",
    "Industrial Services and Manufacturing",
    "Insurance and Risk Management",
    "Interior Design and Architecture",
    "International Trade and Export",
    "IT Consulting and Services",
    "Jewelry and Watchmaking",
    "Journalism and Reporting",
    "Landscaping and Lawn Care",
    "Law and Legal Services",
    "Leisure, Recreation, and Sports",
    "Logistics and Supply Chain Management",
    "Manufacturing and Production",
    "Media and Entertainment",
    "Medical Equipment and Devices",
    "Microfinance and Small Business Lending",
    "Mining and Resource Extraction",
    "Mobile Services and Telecommunications",
    "Music Production and DJ Services",
    "Natural Resource Extraction and Mining",
    "Non-Profit and Charitable Organizations",
    "Oil, Gas, and Petroleum Refining",
    "On-Demand and Gig Economy (Uber, Lyft)",
    "Packaging and Distribution Services",
    "Personal Services (Babysitting, Caregiving)",
    "Petroleum, Gas, and Energy Services",
    "Photography and Videography",
    "Printing, Publishing, and Copy Services",
    "Private Investigation and Security Services",
    "Property Development and Management",
    "Public Relations and Communications",
    "Public Sector and Government Services",
    "Public Transportation and Taxi Services",
    "Real Estate and Property Management",
    "Renewable Energy and Green Tech",
    "Research and Development (R&D)",
    "Restaurants, Cafes, and Food Services",
    "Retail and Consumer Goods",
    "Security and Alarm Services",
    "Shipping, Maritime, and Port Services",
    "Software Development and IT Services",
    "Solar Energy and Installation",
    "Sports Coaching and Training",
    "Street Vendors and Micro-Enterprises",
    "Sustainability Consulting and Green Energy",
    "Telecommunications and Mobile Services",
    "Textile Manufacturing and Apparel",
    "Tourism, Travel Agencies, and Adventure Travel",
    "Transportation, Trucking, and Freight",
    "Utilities and Public Services",
    "Vehicle Rental and Leasing",
    "Veterinary and Pet Services",
    "Virtual Assistant and Administrative Services",
    "Waste Management and Recycling",
    "Web Development and Design Services",
    "Wellness and Spa Services",
    "Wholesale and Distribution",
    "Writing, Editing, and Content Creation",
    "Youth Services and Education",
    "Zoological Services, Botanical Gardens, and Consultancy"
  ];
  
  
  export const legalStructures = [
    "Sole Proprietorship",
  "General Partnership (GP)",
  "Limited Partnership (LP)",
  "Limited Liability Company (LLC)",
  "Corporation (Inc., Corp.)",
  "Non-Profit Organization (NPO)",
  "Joint Venture (JV)",
  "Holding Company",
  "Branch Office",
  "Representative Office",
  ];