# Generated by Django 5.0.6 on 2024-06-04 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('trial', 'Trial'), ('monthly_1', 'Monthly - 1 User'), ('monthly_5', 'Monthly - 5 Users'), ('monthly_10', 'Monthly - 10 Users'), ('monthly_50', 'Monthly - 50 Users'), ('yearly_1', 'Yearly - 1 User'), ('yearly_5', 'Yearly - 5 Users'), ('yearly_10', 'Yearly - 10 Users'), ('yearly_50', 'Yearly - 50 Users')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
