# Generated by Django 5.0.6 on 2024-08-29 10:19

import django.utils.timezone
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_num', models.CharField(editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('ecommerce', 'E-Commerce'), ('SUBSCRIPTION_SERVICES', 'Subscription-Based Services'), ('CONTENT_CREATION', 'Content Creation and Monetization'), ('FREELANCING', 'Freelancing'), ('FOOD_BEVERAGE', 'Food and Beverage'), ('HEALTHCARE', 'Healthcare'), ('REAL_ESTATE_CONSTRUCTION', 'Real Estate and Construction'), ('NON_PROFIT', 'Non-Profit'), ('TRANSPORTATION', 'Transportation'), ('HOSPITALITY', 'Hospitality'), ('PROPERTY_MANAGEMENT', 'Property Management'), ('STORAGE', 'Storage')], max_length=50)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('database_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], max_length=20)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
