# Generated by Django 5.0.6 on 2025-02-22 15:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_founded',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 22))]),
        ),
    ]
