# Generated by Django 5.0.6 on 2024-07-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
    ]
