# Generated by Django 5.0.6 on 2024-09-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free Plan'), ('professional', 'Professional Plan')], max_length=20),
        ),
    ]
