# Generated by Django 5.0.6 on 2024-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'FREE'), ('professional', 'Professional')], default='trial', max_length=20),
        ),
    ]
