# Generated by Django 5.0.6 on 2024-06-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_subscription_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
    ]
