# Generated by Django 5.0.6 on 2025-02-24 00:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_founded',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 2, 24))]),
        ),
    ]
