# Generated by Django 5.0.6 on 2025-03-03 00:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_business_business_subtype_selections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_founded',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 3))]),
        ),
    ]
