# Generated by Django 5.0.6 on 2025-03-03 01:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_business_date_founded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('schema_name', models.CharField(max_length=63)),
                ('table_name', models.CharField(max_length=63)),
                ('export_batch_id', models.UUIDField()),
                ('s3_path', models.CharField(max_length=255)),
                ('export_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('downloaded', models.BooleanField(default=False)),
                ('download_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id'], name='business_ar_tenant__ad8643_idx'), models.Index(fields=['export_date'], name='business_ar_export__22dcf7_idx'), models.Index(fields=['expiry_date'], name='business_ar_expiry__b5a601_idx')],
            },
        ),
    ]
