# Generated by Django 5.0.6 on 2025-03-11 02:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_business_date_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_founded',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 11))]),
        ),
    ]
