// Get environment variables
export const COGNITO_CONFIG = {
  NEXT_PUBLIC_AWS_REGION: process.env.NEXT_PUBLIC_AWS_REGION,
  NEXT_PUBLIC_COGNITO_USER_POOL_ID: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID,
  NEXT_PUBLIC_COGNITO_CLIENT_ID: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
  NEXT_PUBLIC_COGNITO_OAUTH_DOMAIN: process.env.NEXT_PUBLIC_COGNITO_OAUTH_DOMAIN,
  NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
  NEXT_PUBLIC_AUTH_FLOW_TYPE: process.env.NEXT_PUBLIC_AUTH_FLOW_TYPE,
  NEXT_PUBLIC_ALLOWED_AUTH_FLOWS: process.env.NEXT_PUBLIC_ALLOWED_AUTH_FLOWS,
  NEXT_PUBLIC_LOG_LEVEL: process.env.NEXT_PUBLIC_LOG_LEVEL,
  NEXT_PUBLIC_LOG_TO_CONSOLE: process.env.NEXT_PUBLIC_LOG_TO_CONSOLE,
  NEXT_PUBLIC_COGNITO_REDIRECT_SIGNIN: process.env.NEXT_PUBLIC_COGNITO_REDIRECT_SIGNIN,
  NEXT_PUBLIC_COGNITO_REDIRECT_SIGNOUT: process.env.NEXT_PUBLIC_COGNITO_REDIRECT_SIGNOUT,
  NEXT_PUBLIC_TOKEN_REFRESH_BUFFER: process.env.NEXT_PUBLIC_TOKEN_REFRESH_BUFFER,
  NEXT_PUBLIC_TOKEN_REFRESH_RETRY_DELAY: process.env.NEXT_PUBLIC_TOKEN_REFRESH_RETRY_DELAY,
  NEXT_PUBLIC_TOKEN_REFRESH_MAX_RETRIES: process.env.NEXT_PUBLIC_TOKEN_REFRESH_MAX_RETRIES
};

// API configuration
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000';