from django.urls import path
from .views import (
    approve_purchase_return,
    create_procurement,
    create_purchase_return,
    create_vendor,
    create_bill,
    bill_detail,
    bill_list,
    delete_purchase_return,
    procurement_detail,
    procurement_list,
    purchase_return_detail,
    purchase_return_list,
    update_purchase_return,
    approve_purchase_return,
    vendor_list,
    vendor_detail,
    delete_vendor,
    toggle_vendor_status,
    create_purchase_order,
    list_purchase_orders,
    purchase_order_detail,
    create_expense,
    expense_list,
    expense_detail,
 
)

urlpatterns = [
    path('api/vendors/create/', create_vendor, name='create_vendor'),
    path('api/vendors/', vendor_list, name='vendor_list'),
    path('api/vendors/<uuid:pk>/', vendor_detail, name='vendor-detail'),
    path('api/vendors/<uuid:pk>/delete/', delete_vendor, name='delete-vendor'),
    path('api/vendors/<uuid:pk>/toggle-status/', toggle_vendor_status, name='toggle-vendor-status'),
    path('api/bills/', bill_list, name='bill-list'),
    path('api/bills/create/', create_bill, name='create-bill'),
    path('api/bills/<uuid:pk>/', bill_detail, name='bill-detail'),
    path('api/purchase-orders/create/', create_purchase_order, name='create-purchase-order'),
    path('api/purchase-orders/', list_purchase_orders, name='list-purchase-orders'),
    path('api/purchase-orders/<uuid:pk>/', purchase_order_detail, name='purchase-order-detail'),
    path('api/expenses/create/', create_expense, name='create-expense'),
    path('api/expenses/', expense_list, name='expense-list'),
    path('api/expenses/<uuid:pk>/', expense_detail, name='expense-detail'),
    path('api/purchase-returns/create/', create_purchase_return, name='create-purchase-return'),
    path('api/purchase-returns/', purchase_return_list, name='purchase-return-list'),
    path('api/purchase-returns/<uuid:pk>/', purchase_return_detail, name='purchase-return-detail'),
    path('api/purchase-returns/<uuid:pk>/update/', update_purchase_return, name='update-purchase-return'),
    path('api/purchase-returns/<uuid:pk>/delete/', delete_purchase_return, name='delete-purchase-return'),
    path('api/purchase-returns/<uuid:pk>/approve/', approve_purchase_return, name='approve-purchase-return'),
    path('api/procurements/create/', create_procurement, name='create-procurement'),
    path('api/procurements/', procurement_list, name='procurement-list'),
    path('api/procurements/<uuid:pk>/', procurement_detail, name='procurement-detail'),
]