# Generated by Django 4.2.16 on 2025-06-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_ensure_crm_customer_table_and_add_tenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='crm_custome_tenant__db2f56_idx',
            old_name='crm_customer_tenant_idx',
        ),
    ]
