# Generated by Django 4.2.16 on 2025-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_crm_customer_tenant_idx_crm_custome_tenant__db2f56_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant_id', 'account_number'], name='crm_custome_tenant__db2f56_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'account_number'), name='unique_crm_customer_account_number_per_tenant'),
        ),
    ]
