# Generated by Django 4.2.16 on 2025-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_country_paymentgateway_countrypaymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddField(
            model_name='countrypaymentgateway',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddField(
            model_name='tinkitem',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
    ]
