# Generated by Django 5.0.6 on 2024-09-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_plaiditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=255),
        ),
    ]
