# Generated by Django 4.2.16 on 2025-06-27 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_add_secure_banking_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankingauditlog',
            new_name='banking_aud_user_id_99769b_idx',
            old_name='banking_aud_user_id_f6d8ae_idx',
        ),
        migrations.RenameIndex(
            model_name='bankingauditlog',
            new_name='banking_aud_started_320c0d_idx',
            old_name='banking_aud_started_d3c3f4_idx',
        ),
        migrations.AlterField(
            model_name='bankingauditlog',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bankingauditlog',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AlterField(
            model_name='bankingrule',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
    ]
