# Generated by Django 4.2.16 on 2025-07-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_add_purpose_to_bankaccount'),
        ('banking', '0006_rename_banking_aud_user_id_f6d8ae_idx_banking_aud_user_id_99769b_idx_and_more'),
    ]

    operations = [
    ]
