# Generated by Django 5.1.7 on 2025-04-05 14:17

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(blank=True, null=True, verbose_name='Owner ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_num', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
            options={
                'db_table': 'users_business',
            },
        ),
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Business Owner'), ('employee', 'employee')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_plan', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', max_length=20)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_business_owner', models.BooleanField(default=False)),
                ('shopify_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=63, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('setup_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('setup_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=20)),
                ('setup_started_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.business')),
                ('business_type', models.CharField(blank=True, choices=[('ACCOUNTING_BOOKKEEPING', 'Accounting and Bookkeeping'), ('ADMIN_OFFICE_SERVICES', 'Administration and Office Services'), ('ADVENTURE_TOURISM', 'Adventure Tourism and Tour Guides'), ('ADVERTISING_MARKETING', 'Advertising and Marketing'), ('AGRIBUSINESS_CONSULTING', 'Agribusiness and Agricultural Consulting'), ('AGRICULTURAL_MACHINERY', 'Agricultural Machinery'), ('AGRICULTURE_FARMING', 'Agriculture and Farming'), ('HVAC_SERVICES', 'Air Conditioning and HVAC Services'), ('AI_ML_DATA_SCIENCE', 'AI, Machine Learning, and Data Science Services'), ('ANIMAL_PET_SERVICES', 'Animal and Pet Services'), ('APPAREL_CLOTHING', 'Apparel and Clothing'), ('ARCHITECTURE_DESIGN', 'Architecture and Design'), ('ARTS_CRAFTS', 'Arts and Crafts'), ('AUTOMOTIVE_LEASING_REPAIR', 'Automotive, Leasing, and Repair'), ('CHILDCARE_SERVICES', 'Babysitting and Childcare Services'), ('BANKING_FINANCE', 'Banking and Finance'), ('BEAUTY_SERVICES', 'Barbershops, Hair Salons, and Beauty Services'), ('FOOD_BEVERAGE_SERVICES', 'Beverage and Food Services'), ('BIOTECH_PHARMA', 'Biotechnology and Pharmaceuticals'), ('BLOCKCHAIN_CRYPTO', 'Blockchain, Cryptocurrencies, and Exchanges'), ('MEDIA_STREAMING', 'Broadcasting, Media, and Video Streaming'), ('BUSINESS_CONSULTING', 'Business Consulting and Advisory Services'), ('CATERING_FOOD_TRUCKS', 'Catering and Food Trucks'), ('CLEANING_SERVICES', 'Cleaning Services'), ('CLOUD_IT_SERVICES', 'Cloud Computing and IT Services'), ('CONSTRUCTION_CONTRACTING', 'Construction and Contracting'), ('CRAFT_BEVERAGES', 'Craft Beverages (Breweries, Distilleries)'), ('CREATIVE_SERVICES', 'Creative Services (Design, Graphic Design)'), ('CULTURAL_HERITAGE', 'Cultural Heritage and Preservation'), ('CYBERSECURITY', 'Cybersecurity and Risk Management'), ('DATA_ANALYSIS_BI', 'Data Analysis and Business Intelligence'), ('DAIRY_LIVESTOCK', 'Dairy and Livestock Farming'), ('DIGITAL_MARKETING', 'Digital Marketing and Online Services'), ('DJ_ENTERTAINMENT', 'DJ, Music, and Entertainment Services'), ('LOGISTICS', 'Distribution, Freight Forwarding, and Logistics'), ('DRONE_SERVICES', 'Drone and Aerial Services'), ('ECOMMERCE_RETAIL', 'E-commerce and Retail'), ('EDUCATION_TUTORING', 'Education and Tutoring'), ('ELECTRONICS_IT', 'Electronics and IT Equipment'), ('ENERGY_SUSTAINABILITY', 'Energy Auditing and Sustainability Consulting'), ('ENGINEERING_SERVICES', 'Engineering and Technical Services'), ('EVENT_PLANNING', 'Event Planning, Rentals, and Technology'), ('EXPORT_IMPORT', 'Export and Import Trade'), ('FASHION_APPAREL', 'Fashion and Apparel'), ('FILM_TV_PRODUCTION', 'Film, Television, and Media Production'), ('FINANCIAL_PLANNING', 'Financial Planning and Investment Services'), ('FISHING_AQUACULTURE', 'Fishing and Aquaculture'), ('FITNESS_TRAINING', 'Fitness and Personal Training'), ('FLORISTRY_GARDENING', 'Floristry and Gardening'), ('FORESTRY', 'Forestry and Natural Resource Management'), ('FRANCHISING_LICENSING', 'Franchising and Licensing'), ('FREELANCE_GIG_ECONOMY', 'Freelance Platforms and Gig Economy'), ('FUNDRAISING_NONPROFIT', 'Fundraising and Non-Profit Services'), ('FURNITURE_HOME_DECOR', 'Furniture and Home Decor'), ('GREEN_BUILDING', 'Green Building, Renewable Energy, and Solar'), ('HEALTHCARE_MEDICAL', 'Healthcare and Medical Services'), ('HOME_IMPROVEMENT', 'Home Improvement and Renovation'), ('HOSPITALITY', 'Hospitality, Hotels, and Vacation Rentals'), ('HR_RECRUITMENT', 'Human Resources and Recruitment'), ('RENEWABLE_ENERGY', 'Hydroelectric and Wind Energy'), ('INDUSTRIAL_MANUFACTURING', 'Industrial Services and Manufacturing'), ('INSURANCE_RISK', 'Insurance and Risk Management'), ('INTERIOR_DESIGN', 'Interior Design and Architecture'), ('INTERNATIONAL_TRADE', 'International Trade and Export'), ('IT_CONSULTING', 'IT Consulting and Services'), ('JEWELRY_WATCHMAKING', 'Jewelry and Watchmaking'), ('JOURNALISM_REPORTING', 'Journalism and Reporting'), ('LANDSCAPING', 'Landscaping and Lawn Care'), ('LEGAL_SERVICES', 'Law and Legal Services'), ('LEISURE_SPORTS', 'Leisure, Recreation, and Sports'), ('SUPPLY_CHAIN', 'Logistics and Supply Chain Management'), ('MANUFACTURING_PRODUCTION', 'Manufacturing and Production'), ('MEDIA_ENTERTAINMENT', 'Media and Entertainment'), ('MEDICAL_EQUIPMENT', 'Medical Equipment and Devices'), ('MICROFINANCE', 'Microfinance and Small Business Lending'), ('MINING_EXTRACTION', 'Mining and Resource Extraction'), ('MOBILE_TELECOM', 'Mobile Services and Telecommunications'), ('MUSIC_PRODUCTION', 'Music Production and DJ Services'), ('NATURAL_RESOURCES', 'Natural Resource Extraction and Mining'), ('NONPROFIT_CHARITY', 'Non-Profit and Charitable Organizations'), ('OIL_GAS', 'Oil, Gas, and Petroleum Refining'), ('ON_DEMAND_SERVICES', 'On-Demand and Gig Economy (Uber, Lyft)'), ('PACKAGING_DISTRIBUTION', 'Packaging and Distribution Services'), ('PERSONAL_SERVICES', 'Personal Services (Babysitting, Caregiving)'), ('ENERGY_SERVICES', 'Petroleum, Gas, and Energy Services'), ('PHOTOGRAPHY_VIDEOGRAPHY', 'Photography and Videography'), ('PRINTING_PUBLISHING', 'Printing, Publishing, and Copy Services'), ('SECURITY_SERVICES', 'Private Investigation and Security Services'), ('PROPERTY_DEVELOPMENT', 'Property Development and Management'), ('PR_COMMUNICATIONS', 'Public Relations and Communications'), ('PUBLIC_SECTOR', 'Public Sector and Government Services'), ('PUBLIC_TRANSPORTATION', 'Public Transportation and Taxi Services'), ('REAL_ESTATE', 'Real Estate and Property Management'), ('RENEWABLE_TECH', 'Renewable Energy and Green Tech'), ('RESEARCH_DEVELOPMENT', 'Research and Development (R&D)'), ('RESTAURANTS_CAFES', 'Restaurants, Cafes, and Food Services'), ('RETAIL_CONSUMER_GOODS', 'Retail and Consumer Goods'), ('SECURITY_ALARM', 'Security and Alarm Services'), ('SHIPPING_MARITIME', 'Shipping, Maritime, and Port Services'), ('SOFTWARE_DEVELOPMENT', 'Software Development and IT Services'), ('SOLAR_ENERGY', 'Solar Energy and Installation'), ('SPORTS_COACHING', 'Sports Coaching and Training'), ('STREET_VENDORS', 'Street Vendors and Micro-Enterprises'), ('SUSTAINABILITY_CONSULTING', 'Sustainability Consulting and Green Energy'), ('TELECOMMUNICATIONS', 'Telecommunications and Mobile Services'), ('TEXTILE_MANUFACTURING', 'Textile Manufacturing and Apparel'), ('TOURISM_TRAVEL', 'Tourism, Travel Agencies, and Adventure Travel'), ('TRANSPORTATION_FREIGHT', 'Transportation, Trucking, and Freight'), ('UTILITIES', 'Utilities and Public Services'), ('VEHICLE_RENTAL', 'Vehicle Rental and Leasing'), ('VETERINARY_SERVICES', 'Veterinary and Pet Services'), ('VIRTUAL_ASSISTANT', 'Virtual Assistant and Administrative Services'), ('WASTE_MANAGEMENT', 'Waste Management and Recycling'), ('WEB_DEVELOPMENT', 'Web Development and Design Services'), ('WELLNESS_SPA', 'Wellness and Spa Services'), ('WHOLESALE_DISTRIBUTION', 'Wholesale and Distribution'), ('WRITING_EDITING', 'Writing, Editing, and Content Creation'), ('YOUTH_SERVICES', 'Youth Services and Education'), ('ZOOLOGICAL_SERVICES', 'Zoological Services, Botanical Gardens, and Consultancy')], max_length=50, null=True)),
                ('business_subtype_selections', models.JSONField(blank=True, default=dict)),
                ('legal_structure', models.CharField(choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('GENERAL_PARTNERSHIP', 'General Partnership (GP)'), ('LIMITED_PARTNERSHIP', 'Limited Partnership (LP)'), ('LLC', 'Limited Liability Company (LLC)'), ('CORPORATION', 'Corporation (Inc., Corp.)'), ('NON_PROFIT', 'Non-Profit Organization (NPO)'), ('JOINT_VENTURE', 'Joint Venture (JV)'), ('HOLDING_COMPANY', 'Holding Company'), ('BRANCH_OFFICE', 'Branch Office'), ('REPRESENTATIVE_OFFICE', 'Representative Office')], default='SOLE_PROPRIETORSHIP', max_length=50)),
                ('date_founded', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
            ],
            options={
                'db_table': 'users_business_details',
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_num'], name='users_busin_busines_de1003_idx'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to='users.business'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.business'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='businessmember',
            unique_together={('business', 'user')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant_id'], name='users_userp_tenant__d11818_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['business_id'], name='users_userp_busines_4c5066_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_profile'),
        ),
    ]
