services:
  - type: web
    name: dott-frontend
    runtime: node
    buildCommand: pnpm install && pnpm run build:render
    startCommand: pnpm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_AUTH0_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_AUTH0_CLIENT_ID
        sync: false
      - key: NEXT_PUBLIC_AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_SECRET
        sync: false
      - key: AUTH0_BASE_URL
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_SCOPE
        sync: false
      - key: NEXT_PUBLIC_CRISP_WEBSITE_ID
        sync: false
    healthCheckPath: /api/auth/session