services:
  - type: web
    name: dott-front
    runtime: docker
    region: oregon
    dockerfilePath: Dockerfile
    dockerContext: frontend/pyfactor_next
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=3584
    headers:
      - path: /_next/static/css/*
        name: Content-Type
        value: text/css
      - path: /_next/static/css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
