# Generated by Django 5.1.7 on 2025-04-27 00:53

import django.core.validators
import django.db.models.deletion
import hr.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_employee_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('approval_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('input_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10)),
                ('class_tiers', models.JSONField(default=dict, help_text='JSON containing PTO tiers by role')),
                ('default_pto_days_per_year', models.PositiveIntegerField(default=10)),
                ('default_sick_days_per_year', models.PositiveIntegerField(default=5)),
                ('allow_overtime', models.BooleanField(default=True)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))])),
                ('require_manager_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timesheet Setting',
                'verbose_name_plural': 'Timesheet Settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=True)),
                ('recurring_yearly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Holiday',
                'verbose_name_plural': 'Company Holidays',
                'unique_together': {('business_id', 'date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('PTO', 'Paid Time Off'), ('SICK', 'Sick Leave')], max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_off', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Time Off Request',
                'verbose_name_plural': 'Time Off Requests',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('total_regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'unique_together': {('employee', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='TimeOffBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=hr.models.get_current_year)),
                ('pto_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sick_leave_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pto_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sick_leave_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pto_carryover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sick_leave_carryover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_balance', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Time Off Balance',
                'verbose_name_plural': 'Time Off Balances',
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr.timesheet')),
            ],
            options={
                'verbose_name': 'Timesheet Entry',
                'verbose_name_plural': 'Timesheet Entries',
                'unique_together': {('timesheet', 'date')},
            },
        ),
    ]
