# Generated by Django 5.1.7 on 2025-04-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_timesheetsetting_companyholiday_timeoffrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffbalance',
            name='business_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='business_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='business_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
