# Generated by Django 5.1.7 on 2025-04-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_timeoffbalance_business_id_and_more'),
        ('hr', '0008_timesheet_timesheet_number'),
    ]

    operations = [
    ]
