# Generated by Django 5.0.6 on 2024-10-16 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('legal_structure', models.CharField(blank=True, max_length=100)),
                ('date_founded', models.DateField(blank=True, null=True)),
                ('subscription_type', models.CharField(blank=True, max_length=50)),
                ('current_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_status', models.CharField(choices=[('step1', 'Step 1'), ('step2', 'Step 2'), ('step3', 'Step 3'), ('step4', 'Step 4'), ('complete', 'Complete')], default='step1', max_length=20)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='onboardingprogress',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_onboarding_progress'),
        ),
    ]
