# Generated by Django 5.0.6 on 2025-02-09 23:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_status', models.CharField(choices=[('notstarted', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='notstarted', max_length=256)),
                ('account_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=9, validators=[django.core.validators.MinLengthValidator(6)])),
                ('user_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin')], default='owner', max_length=6, validators=[django.core.validators.MinLengthValidator(4)])),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', max_length=12, validators=[django.core.validators.MinLengthValidator(4)])),
                ('current_step', models.CharField(choices=[('notstarted', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='notstarted', max_length=256)),
                ('next_step', models.CharField(blank=True, choices=[('notstarted', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], max_length=256, null=True)),
                ('completed_steps', models.JSONField(default=list)),
                ('last_active_step', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('access_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attribute_version', models.CharField(default='1.0.0', max_length=10)),
                ('preferences', models.JSONField(default=dict, help_text='User preferences stored as JSON')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='business.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
