# Generated by Django 5.0.6 on 2025-02-01 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_plan', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', help_text='Selected subscription plan', max_length=20)),
                ('current_step', models.CharField(choices=[('business-info', 'Business Information'), ('subscription', 'Subscription Selection'), ('payment', 'Payment'), ('setup', 'Database Setup'), ('complete', 'Complete')], default='business-info', max_length=20)),
                ('next_step', models.CharField(blank=True, choices=[('business-info', 'Business Information'), ('subscription', 'Subscription Selection'), ('payment', 'Payment'), ('setup', 'Database Setup'), ('complete', 'Complete')], default='subscription', max_length=20, null=True)),
                ('onboarding_status', models.CharField(choices=[('business-info', 'Business Information'), ('subscription', 'Subscription Selection'), ('payment', 'Payment'), ('setup', 'Database Setup'), ('complete', 'Complete')], default='business-info', help_text='Indicates the current stage of the onboarding process.', max_length=20)),
                ('subscription_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', help_text="Status of the user's subscription process", max_length=20)),
                ('database_provisioning_status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('active', 'Active'), ('error', 'Error'), ('deleted', 'Deleted')], default='not_started', help_text='Status of the physical database provisioning process', max_length=50)),
                ('technical_setup_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('configuring', 'Configuring'), ('data_setup', 'Initial Data Setup'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the overall technical setup including configuration and initial data', max_length=50)),
                ('payment_completed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('last_payment_attempt', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('database_setup_task_id', models.CharField(blank=True, help_text='Celery task ID for database setup', max_length=255, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255, null=True)),
                ('setup_progress', models.IntegerField(default=0)),
                ('setup_started_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_error', models.TextField(blank=True, null=True)),
                ('setup_retries', models.IntegerField(default=0)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(blank=True, help_text="Reference to the user's business information", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_business', to='business.business')),
                ('subscription', models.OneToOneField(blank=True, help_text='Reference to the subscription during onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_subscription', to='business.subscription')),
                ('user', models.ForeignKey(help_text='The user associated with this onboarding process', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_progress',
                'indexes': [models.Index(fields=['onboarding_status'], name='onboarding__onboard_2b7ff4_idx'), models.Index(fields=['database_provisioning_status'], name='onboarding__databas_87e474_idx'), models.Index(fields=['technical_setup_status'], name='onboarding__technic_32bc54_idx'), models.Index(fields=['user'], name='onboarding__user_id_7bb12f_idx'), models.Index(fields=['created_at'], name='onboarding__created_953790_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingprogress',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_onboarding_progress'),
        ),
    ]
