# Generated by Django 5.1.7 on 2025-03-30 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='business_id',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='billing_cycle',
            field=models.CharField(blank=True, default='monthly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_progresses', to='users.business'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='payment_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='rls_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='rls_setup_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='schema_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='setup_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='current_step',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='business-info', max_length=50),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='next_step',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='subscription', max_length=50),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='business-info', max_length=50),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences stored as JSON', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='selected_plan',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', max_length=20, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='setup_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', max_length=20, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee')], default='owner', max_length=20, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
