# Generated by Django 5.0.6 on 2025-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingprogress',
            name='current_step',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='notstarted', max_length=256),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='next_step',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='notstarted', max_length=256),
        ),
    ]
