# Generated by Django 5.0.6 on 2025-02-28 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_onboardingprogress_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingprogress',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee')], default='owner', max_length=10, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
