# Generated by Django 5.0.6 on 2025-03-14 23:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_remove_onboardingprogress_business_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Onboarding Progress', 'verbose_name_plural': 'Onboarding Progress Records'},
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='user_id',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='user',
            field=models.OneToOneField(default='8aa47ee0-aa92-4f50-98e4-2584c9efd714', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='access_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=9, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='attribute_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='business_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='current_step',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='notstarted', max_length=256),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='last_active_step',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='next_step',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('business-info', 'Business Info'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('setup', 'Setup'), ('complete', 'Complete')], default='notstarted', max_length=256),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='preferences',
            field=models.JSONField(default=dict, help_text='User preferences stored as JSON'),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='selected_plan',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', max_length=12, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='setup_error',
            field=models.TextField(blank=True, help_text='Last setup error message', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='free', max_length=12, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee')], default='owner', max_length=10, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterModelTable(
            name='onboardingprogress',
            table=None,
        ),
    ]
