# Generated by Django 5.1.7 on 2025-03-30 00:12

from django.db import migrations, models
import uuid
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
        ('onboarding', '0002_remove_onboardingprogress_business_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='custom_auth.user')),
                ('business_id', models.UUIDField(blank=True, null=True)),  # Store as UUID field instead of ForeignKey
                
                # Status fields
                ('onboarding_status', models.CharField(default='business-info', max_length=50)),
                ('current_step', models.CharField(default='business-info', max_length=50)),
                ('next_step', models.CharField(default='subscription', max_length=50)),
                ('completed_steps', models.JSONField(default=list)),
                
                # Subscription and plan data
                ('selected_plan', models.CharField(default='free', max_length=20)),
                ('subscription_plan', models.CharField(default='free', max_length=20, null=True, blank=True)),
                ('subscription_status', models.CharField(max_length=20, null=True, blank=True)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20, null=True, blank=True)),
                
                # Payment tracking
                ('payment_completed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=50, null=True, blank=True)),
                ('payment_id', models.CharField(max_length=100, null=True, blank=True)),
                ('payment_timestamp', models.DateTimeField(null=True, blank=True)),
                
                # RLS setup tracking
                ('rls_setup_completed', models.BooleanField(default=False)),
                ('rls_setup_timestamp', models.DateTimeField(null=True, blank=True)),
                
                # Setup status tracking  
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_timestamp', models.DateTimeField(null=True, blank=True)),
                ('setup_error', models.TextField(null=True, blank=True)),
                ('database_setup_task_id', models.CharField(max_length=255, null=True, blank=True)),
                
                # Schema information
                ('schema_name', models.CharField(max_length=63, null=True, blank=True)),
                
                # Metadata
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('account_status', models.CharField(default='pending', max_length=20)),
                ('user_role', models.CharField(default='owner', max_length=20)),
                ('attribute_version', models.CharField(default='1.0.0', max_length=10)),
                
                # Preferences and settings
                ('preferences', models.JSONField(default=dict, null=True, blank=True)),
                ('metadata', models.JSONField(default=dict, null=True, blank=True)),
            ],
            options={
                'db_table': 'onboarding_onboardingprogress',
            },
        ),
    ]
