# Generated by Django 5.0.6 on 2025-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingprogress_completed_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='selectedPlan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('professional', 'Professional')], max_length=50),
        ),
    ]
