# Generated by Django 5.0.6 on 2024-10-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardingprogress_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='is_onboarded',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='onboarding_status',
            field=models.CharField(choices=[('step1', 'Step 1'), ('step2', 'Step 2'), ('payment', 'Payment'), ('complete', 'Complete')], default='step1', max_length=20),
        ),
    ]
