# Generated by Django 5.1.7 on 2025-04-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_onboardingprogress_options_and_more'),
        ('onboarding', 'custom_tenant_migration'),
    ]

    operations = [
    ]
