ACCOUNT_TYPES = {
    'Cash': 0,
    'Accounts Receivable': 1,
    'Inventory': 2,
    'Prepaid Expenses': 3,
    'Property, Plant, and Equipment': 4,
    'Accumulated Depreciation': 5,
    'Accounts Payable': 6,
    'Accrued Expenses': 7,
    'Unearned Revenue': 8,
    'Long-term Debt': 9,
    'Owners Equity': 10,
    'Sales Revenue': 11,
    'Service Revenue': 12,
    'Interest Income': 13,
    'Salaries Expense': 15,
    'Rent Expense': 16,
    'Utilities Expense': 17,
    'Insurance Expense': 18,
    'Depreciation Expense': 19,
    'Interest Expense': 20,
    'Advertising Expense': 21,
    'Office Supplies Expense': 22,
    'Payroll Tax Expense': 23,
    'Miscellaneous Expense': 24,
    'Sales Tax Payable': 25,
    'Current Asset': 1000,
    'Current Liability': 2000,
    'Equity': 3000,
    'Revenue': 4000,
    'Operating Expense': 5000,
    'Cost of Goods Sold': 6000,
    'Non-Operating Expense': 6100,
}