# Generated by Django 4.2.9 on 2025-01-07 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150, blank=True)),
                ('last_name', models.CharField(max_length=150, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(max_length=20, unique=True, null=True, blank=True)),
                ('department', models.CharField(max_length=50, choices=[
                    ('support', 'Customer Support'),
                    ('product', 'Product Team'),
                    ('engineering', 'Engineering'),
                    ('sales', 'Sales'),
                    ('management', 'Management'),
                    ('finance', 'Finance'),
                ], default='support')),
                ('admin_role', models.CharField(max_length=20, choices=[
                    ('super_admin', 'Super Admin'),
                    ('admin', 'Admin'),
                    ('moderator', 'Moderator'),
                    ('support_agent', 'Support Agent'),
                    ('read_only', 'Read Only'),
                ], default='support_agent')),
                ('can_send_notifications', models.BooleanField(default=False)),
                ('can_view_all_users', models.BooleanField(default=False)),
                ('can_view_feedback', models.BooleanField(default=True)),
                ('can_moderate_content', models.BooleanField(default=False)),
                ('ip_whitelist', models.JSONField(default=list, blank=True)),
                ('phone_number', models.CharField(max_length=20, blank=True)),
                ('slack_user_id', models.CharField(max_length=50, blank=True)),
                ('last_login', models.DateTimeField(null=True, blank=True)),
                ('last_login_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_users',
            },
        ),
    ]