# Generated by Django 4.2.9 on 2025-01-07 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50, choices=[
                    ('system', 'System Announcements'),
                    ('product', 'Product Updates'),
                    ('security', 'Security Alerts'),
                    ('maintenance', 'Maintenance Notices'),
                    ('billing', 'Billing Updates'),
                    ('feature', 'New Features'),
                    ('tax', 'Tax Updates'),
                ])),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('icon_type', models.CharField(max_length=20, choices=[
                    ('info', 'Information'),
                    ('warning', 'Warning'),
                    ('error', 'Error'),
                    ('success', 'Success'),
                    ('announcement', 'Announcement'),
                ], default='info')),
                ('priority', models.CharField(max_length=10, choices=[
                    ('low', 'Low'),
                    ('medium', 'Medium'),
                    ('high', 'High'),
                    ('urgent', 'Urgent'),
                ], default='medium')),
                ('available_variables', models.JSONField(default=dict, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to='notifications.adminuser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon_type', models.CharField(max_length=20, choices=[
                    ('info', 'Information'),
                    ('warning', 'Warning'),
                    ('error', 'Error'),
                    ('success', 'Success'),
                    ('announcement', 'Announcement'),
                    ('tax_update', 'Tax Update'),
                ], default='info')),
                ('category', models.CharField(max_length=50, blank=True, null=True, choices=[
                    ('announcement', 'Announcement'),
                    ('update', 'Update'),
                    ('alert', 'Alert'),
                    ('promotion', 'Promotion'),
                    ('system', 'System'),
                    ('tax', 'Tax Update'),
                    ('payment', 'Payment'),
                ])),
                ('target_type', models.CharField(max_length=20, choices=[
                    ('all_users', 'All Users'),
                    ('specific_users', 'Specific Users'),
                    ('by_plan', 'By Subscription Plan'),
                    ('by_role', 'By User Role'),
                    ('by_country', 'By Country'),
                    ('active_users', 'Active Users Only'),
                ])),
                ('target_criteria', models.JSONField(default=dict, blank=True)),
                ('priority', models.CharField(max_length=10, choices=[
                    ('low', 'Low'),
                    ('medium', 'Medium'),
                    ('high', 'High'),
                    ('urgent', 'Urgent'),
                ], default='medium')),
                ('send_email', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('auto_dismiss_after', models.IntegerField(null=True, blank=True)),
                ('scheduled_for', models.DateTimeField(null=True, blank=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                ('status', models.CharField(max_length=10, choices=[
                    ('draft', 'Draft'),
                    ('scheduled', 'Scheduled'),
                    ('sending', 'Sending'),
                    ('sent', 'Sent'),
                    ('failed', 'Failed'),
                    ('cancelled', 'Cancelled'),
                ], default='draft')),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.adminuser')),
                ('template_used', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='notifications', to='notifications.notificationtemplate')),
                ('action_button_text', models.CharField(max_length=50, blank=True)),
                ('action_button_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_8a6c8f_idx'),
                    models.Index(fields=['target_type', 'created_at'], name='notificatio_target__2e7c3f_idx'),
                    models.Index(fields=['priority', 'status'], name='notificatio_priorit_0a6d6f_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('tenant_id', models.UUIDField(db_index=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
                ('user_email', models.EmailField()),
                ('user_name', models.CharField(max_length=200, blank=True)),
                ('delivery_status', models.CharField(max_length=10, choices=[
                    ('pending', 'Pending'),
                    ('delivered', 'Delivered'),
                    ('failed', 'Failed'),
                    ('bounced', 'Bounced'),
                ], default='pending')),
                ('is_read', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('delivered_at', models.DateTimeField(null=True, blank=True)),
                ('read_at', models.DateTimeField(null=True, blank=True)),
                ('clicked_at', models.DateTimeField(null=True, blank=True)),
                ('dismissed_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_recipients',
                'unique_together': {('notification', 'tenant_id', 'user_email')},
                'indexes': [
                    models.Index(fields=['tenant_id', 'user_email', 'is_read'], name='notificatio_tenant__0e5f8a_idx'),
                    models.Index(fields=['notification', 'delivery_status'], name='notificatio_notific_2e7c3f_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='notifications.adminuser')),
                ('action', models.CharField(max_length=50)),
                ('action_details', models.JSONField(default=dict)),
                ('object_type', models.CharField(max_length=50, blank=True)),
                ('object_id', models.CharField(max_length=100, blank=True)),
                ('status', models.CharField(max_length=20, choices=[
                    ('success', 'Success'),
                    ('failure', 'Failure'),
                    ('partial', 'Partial Success'),
                ], default='success')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['admin_user', 'created_at'], name='admin_audit_admin_u_0a6d6f_idx'),
                    models.Index(fields=['action', 'created_at'], name='admin_audit_action_2e7c3f_idx'),
                ],
            },
        ),
    ]