#!/bin/bash

echo "🧹 CLOUDFLARE CACHE PURGE INSTRUCTIONS"
echo "====================================="
echo ""
echo "To purge Cloudflare cache manually:"
echo ""
echo "1. Go to https://dash.cloudflare.com"
echo "2. Select your domain: dottapps.com"
echo "3. Navigate to: Caching > Configuration"
echo "4. Click 'Purge Everything' button"
echo "5. Confirm the purge"
echo ""
echo "Alternative: Purge specific URLs"
echo "1. Same location: Caching > Configuration"
echo "2. Click 'Custom Purge'"
echo "3. Enter URLs to purge:"
echo "   - https://app.dottapps.com/*"
echo "   - https://dottapps.com/*"
echo "   - https://www.dottapps.com/*"
echo ""
echo "To automate this in the future:"
echo "1. Get your Zone ID from Cloudflare dashboard (right sidebar)"
echo "2. Create an API token: My Profile > API Tokens > Create Token"
echo "3. Use 'Edit zone' template, select your zone"
echo "4. Update this script with your credentials"
echo ""
echo "Press Enter when you've completed the cache purge..."
read -r