# Generated by Django 5.0.6 on 2025-03-22 17:59

import django.db.models.deletion
import payroll.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payroll_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('is_international', models.BooleanField(default=False)),
                ('service_type', models.CharField(choices=[('full', 'Full-Service'), ('self', 'Self-Service')], default='full', max_length=10)),
                ('filing_instructions', models.TextField(blank=True, null=True)),
                ('tax_authority_links', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=payroll.models.default_due_datetime)),
                ('updated_at', models.DateTimeField(default=payroll.models.default_due_datetime)),
                ('tax_filings_created', models.BooleanField(default=False)),
                ('tax_filings_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('show_usd_comparison', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('federal_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('medicare_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('social_security_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_withholdings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=20)),
                ('tax_year', models.IntegerField()),
                ('file', models.FileField(upload_to='tax_forms/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timesheet_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('start_date', models.DateField(default=payroll.models.get_current_datetime)),
                ('end_date', models.DateField(default=payroll.models.get_current_datetime)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=payroll.models.default_due_datetime)),
                ('updated_at', models.DateTimeField(default=payroll.models.default_due_datetime)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.timesheet')),
            ],
        ),
    ]
