# Generated by Django 5.0.6 on 2025-02-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='country_code',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='exchange_rate_to_usd',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='filing_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='service_type',
            field=models.CharField(choices=[('full', 'Full-Service'), ('self', 'Self-Service')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='show_usd_comparison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='tax_authority_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='tax_filings_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='tax_filings_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payrolltransaction',
            name='additional_withholdings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrolltransaction',
            name='federal_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrolltransaction',
            name='medicare_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrolltransaction',
            name='social_security_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrolltransaction',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payrolltransaction',
            name='state_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
