# Generated by Django 5.0.4 on 2025-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(
                default='UTC',
                max_length=50,
                null=True,
                blank=True,
                verbose_name='User Timezone',
                help_text='User timezone (e.g., America/New_York) in IANA format'
            ),
        ),
    ]