# Generated by Django 5.1.7 on 2025-03-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rls_enabled',
            field=models.BooleanField(default=True, help_text='Whether Row Level Security is enabled for this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rls_setup_date',
            field=models.DateTimeField(blank=True, help_text='When RLS was first set up for this tenant', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='setup_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('active', 'Active'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=20),
        ),
    ]
