# Generated by Django 5.1.7 on 2025-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
