# Generated by Django 5.0.6 on 2025-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_cognito_sub_alter_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='setup_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
