# Generated by Django migration

from django.db import migrations


def populate_page_permissions(apps, schema_editor):
    PagePermission = apps.get_model('custom_auth', 'PagePermission')
    
    # Define all pages in the system
    pages = [
        # Dashboard
        {'name': 'Dashboard', 'path': '/dashboard', 'category': 'General', 'description': 'Main dashboard overview'},
        
        # Sales & Inventory
        {'name': 'Products', 'path': '/dashboard/products', 'category': 'Sales', 'description': 'Product management'},
        {'name': 'Services', 'path': '/dashboard/services', 'category': 'Sales', 'description': 'Service management'},
        {'name': 'Customers', 'path': '/dashboard/customers', 'category': 'Sales', 'description': 'Customer management'},
        {'name': 'Estimates', 'path': '/dashboard/estimates', 'category': 'Sales', 'description': 'Estimate management'},
        {'name': 'Invoices', 'path': '/dashboard/invoices', 'category': 'Sales', 'description': 'Invoice management'},
        {'name': 'Inventory', 'path': '/inventory', 'category': 'Sales', 'description': 'Inventory management'},
        
        # Finance
        {'name': 'Payments', 'path': '/dashboard/payments', 'category': 'Finance', 'description': 'Payment processing'},
        {'name': 'Expenses', 'path': '/dashboard/expenses', 'category': 'Finance', 'description': 'Expense tracking'},
        {'name': 'Reports', 'path': '/dashboard/reports', 'category': 'Finance', 'description': 'Financial reports'},
        
        # HR
        {'name': 'Employees', 'path': '/dashboard/employees', 'category': 'HR', 'description': 'Employee management'},
        {'name': 'Payroll', 'path': '/dashboard/payroll', 'category': 'HR', 'description': 'Payroll processing'},
        {'name': 'Timesheets', 'path': '/dashboard/timesheets', 'category': 'HR', 'description': 'Time tracking'},
        
        # Settings (Special - Owner/Admin only)
        {'name': 'Settings', 'path': '/settings', 'category': 'System', 'description': 'System settings'},
        {'name': 'User Management', 'path': '/settings/users', 'category': 'System', 'description': 'Manage users and permissions'},
        {'name': 'Subscription', 'path': '/settings/subscription', 'category': 'System', 'description': 'Subscription and billing - Owner only'},
        {'name': 'Account Closure', 'path': '/settings/close-account', 'category': 'System', 'description': 'Close account - Owner only'},
    ]
    
    # Create PagePermission entries
    for page_data in pages:
        PagePermission.objects.create(**page_data)


def reverse_populate_page_permissions(apps, schema_editor):
    PagePermission = apps.get_model('custom_auth', 'PagePermission')
    PagePermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_add_rbac_models'),
    ]

    operations = [
        migrations.RunPython(populate_page_permissions, reverse_populate_page_permissions),
    ]