# Generated by Django 5.0.6 on 2025-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_tenant_setup_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('Freelancer', 'Freelancer'), ('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('COO', 'Chief Operating Officer'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('SUPERVISOR', 'Supervisor'), ('TEAM_LEAD', 'Team Lead'), ('ACCOUNTANT', 'Accountant'), ('FINANCIAL_ANALYST', 'Financial Analyst'), ('HR_MANAGER', 'HR Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('SALES_MANAGER', 'Sales Manager'), ('CUSTOMER_SERVICE_REP', 'Customer Service Representative'), ('ADMINISTRATIVE_ASSISTANT', 'Administrative Assistant'), ('CLERK', 'Clerk'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('CONSULTANT', 'Consultant'), ('STAFF', 'Staff'), ('EMPLOYEE', 'Employee'), ('ENGINEER', 'Engineer'), ('CONTRACTOR', 'Contractor'), ('TRAINER', 'Trainer'), ('IT_ADMIN', 'IT Admin'), ('IT_SUPPORT', 'IT Support'), ('OTHER', 'Other')], default='OWNER', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Business Owner'), ('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee')], default='OWNER', max_length=20),
        ),
    ]
