# Generated by Django 5.0.6 on 2025-03-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_user_occupation_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='storage_quota_bytes',
            field=models.BigIntegerField(default=2147483648),
        ),
    ]
