# Generated by Django 4.2.16 on 2025-06-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_add_auth0_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cognito_sub',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email verification status from Auth0'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Full name from Auth0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, help_text='Profile picture URL from Auth0', null=True),
        ),
    ]
