# Generated by Django 5.0.6 on 2025-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_tenant_storage_quota_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='archive_expiry_notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='archive_expiry_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='archive_retention_days',
            field=models.IntegerField(default=2555),
        ),
        migrations.AddField(
            model_name='tenant',
            name='archive_user_decision',
            field=models.CharField(choices=[('pending', 'Pending Decision'), ('export', 'Export and Delete'), ('delete', 'Delete Without Export'), ('extend', 'Extend Retention')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
