# Generated by Django 5.0.6 on 2025-03-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_tenant_archive_expiry_notification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='database_setup_task_id',
        ),
    ]
