# Generated by Django 4.2.16 on 2025-06-12 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_add_deletion_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountdeletionlog',
            new_name='custom_auth_user_em_b53a96_idx',
            old_name='custom_auth_accountdeletionlog_user_email_idx',
        ),
        migrations.RenameIndex(
            model_name='accountdeletionlog',
            new_name='custom_auth_deletio_4e52a5_idx',
            old_name='custom_auth_accountdeletionlog_deletion_date_idx',
        ),
        migrations.AlterField(
            model_name='accountdeletionlog',
            name='deletion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
