# Generated by Django 4.2.16 on 2025-06-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0014_set_first_user_as_owner'),
        ('custom_auth', '0010_add_subscription_plan_to_user'),
    ]

    operations = [
    ]
