"""
Universal migration to add tenant_id to all models for complete tenant isolation.
"""
from django.db import migrations, models

class Migration(migrations.Migration):
    
    dependencies = []  # Will be filled by makemigrations
    
    operations = [
        # This migration adds tenant_id to all models
        # The actual operations will be generated by makemigrations
    ]
