# Generated by Django 5.1.7 on 2025-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
