# Generated by Django 5.1.7 on 2025-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_tenant__6738c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_tenant__208840_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tenant',
        ),
        migrations.AddField(
            model_name='product',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'name'], name='inventory_p_tenant__6738c2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'sku'], name='inventory_p_tenant__208840_idx'),
        ),
    ]
