# Generated by Django 5.0.6 on 2025-03-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_performance_indexes'),
        ('inventory', '0002_customchargeplan_department_product_and_more'),
    ]

    operations = [
    ]
