# Generated by Django 5.0.6 on 2025-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_merge_20250309_1949'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_name_1aa0b8_idx',
            old_name='inv_name_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_quantit_76849a_idx',
            old_name='inv_qty_reorder_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_categor_a229da_idx',
            old_name='inv_cat_supp_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_stock_q_05543d_idx',
            old_name='prod_qty_reorder_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_is_for__3f6d83_idx',
            old_name='prod_sale_price_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_created_081871_idx',
            old_name='prod_created_idx',
        ),
        migrations.AlterField(
            model_name='service',
            name='is_recurring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_for_sale', 'stock_quantity'], name='inventory_p_is_for__585cac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['department', 'stock_quantity'], name='inventory_p_departm_38d49e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_recurring'], name='inventory_s_is_recu_b8c568_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_for_sale', 'price'], name='inventory_s_is_for__b3db46_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='inventory_s_created_4e6d87_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_for_sale', 'is_recurring'], name='inventory_s_is_for__32e1b6_idx'),
        ),
    ]
