# Generated by Django 5.1.7 on 2025-04-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_supplier_fields_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
    ]
