# Generated by Django 4.2.16 on 2025-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_tenant_to_service'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='inventory_s_name_80acbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='inventory_s_service_284e92_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='inventory_s_tenant__c4f8c9_idx',
            old_name='inventory_s_tenant__name_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='inventory_s_tenant__27047c_idx',
            old_name='inventory_s_tenant__code_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tenant',
        ),
        migrations.AddField(
            model_name='service',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='The tenant ID this record belongs to. Used by Row Level Security.', null=True),
        ),
        migrations.AlterModelTable(
            name='service',
            table='inventory_service',
        ),
    ]
