# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_service_inventory_s_name_80acbf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(
                choices=[('product', 'Product for Sale'), ('supply', 'Supply/Material')],
                db_index=True,
                default='product',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Default markup % when billing to customers',
                max_digits=5
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='is_billable',
            field=models.BooleanField(
                default=True,
                help_text='Can this supply be billed to customers?'
            ),
        ),
    ]