# Generated by Django 4.2.16 on 2025-07-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_material_tracking'),
        ('inventory', '0011_add_pricing_model_fields'),
    ]

    operations = [
    ]
