"""
Comprehensive country name to ISO code mapping
"""

# Comprehensive mapping of country names (in various formats) to ISO codes
COUNTRY_NAME_TO_CODE = {
    # Africa
    'ALGERIA': 'DZ',
    'ANGOLA': 'AO',
    'BENIN': 'BJ',
    'BOTSWANA': 'BW',
    'BURKINA FASO': 'BF',
    'BURUNDI': 'BI',
    'CAMEROON': 'CM',
    'CAPE VERDE': 'CV',
    'CENTRAL AFRICAN REPUBLIC': 'CF',
    'CHAD': 'TD',
    'COMOROS': 'KM',
    'CONGO': 'CG',
    'DEMOCRATIC REPUBLIC OF THE CONGO': 'CD',
    'DJIBOUTI': 'DJ',
    'EGYPT': 'EG',
    'EQUATORIAL GUINEA': 'GQ',
    'ERITREA': 'ER',
    'ETHIOPIA': 'ET',
    'GABON': 'GA',
    'GAMBIA': 'GM',
    'GHANA': 'GH',
    'GUINEA': 'GN',
    'GUINEA-BISSAU': 'GW',
    'IVORY COAST': 'CI',
    'KENYA': 'KE',
    'LESOTHO': 'LS',
    'LIBERIA': 'LR',
    'LIBYA': 'LY',
    'MADAGASCAR': 'MG',
    'MALAWI': 'MW',
    'MALI': 'ML',
    'MAURITANIA': 'MR',
    'MAURITIUS': 'MU',
    'MOROCCO': 'MA',
    'MOZAMBIQUE': 'MZ',
    'NAMIBIA': 'NA',
    'NIGER': 'NE',
    'NIGERIA': 'NG',
    'RWANDA': 'RW',
    'SAO TOME AND PRINCIPE': 'ST',
    'SENEGAL': 'SN',
    'SEYCHELLES': 'SC',
    'SIERRA LEONE': 'SL',
    'SOMALIA': 'SO',
    'SOUTH AFRICA': 'ZA',
    'SOUTH SUDAN': 'SS',
    'SUDAN': 'SD',
    'SWAZILAND': 'SZ',
    'ESWATINI': 'SZ',
    'TANZANIA': 'TZ',
    'TOGO': 'TG',
    'TUNISIA': 'TN',
    'UGANDA': 'UG',
    'ZAMBIA': 'ZM',
    'ZIMBABWE': 'ZW',
    
    # Americas
    'ANTIGUA AND BARBUDA': 'AG',
    'ARGENTINA': 'AR',
    'BAHAMAS': 'BS',
    'BARBADOS': 'BB',
    'BELIZE': 'BZ',
    'BOLIVIA': 'BO',
    'BRAZIL': 'BR',
    'CANADA': 'CA',
    'CHILE': 'CL',
    'COLOMBIA': 'CO',
    'COSTA RICA': 'CR',
    'CUBA': 'CU',
    'DOMINICA': 'DM',
    'DOMINICAN REPUBLIC': 'DO',
    'ECUADOR': 'EC',
    'EL SALVADOR': 'SV',
    'GRENADA': 'GD',
    'GUATEMALA': 'GT',
    'GUYANA': 'GY',
    'HAITI': 'HT',
    'HONDURAS': 'HN',
    'JAMAICA': 'JM',
    'MEXICO': 'MX',
    'NICARAGUA': 'NI',
    'PANAMA': 'PA',
    'PARAGUAY': 'PY',
    'PERU': 'PE',
    'SAINT KITTS AND NEVIS': 'KN',
    'SAINT LUCIA': 'LC',
    'SAINT VINCENT AND THE GRENADINES': 'VC',
    'SURINAME': 'SR',
    'TRINIDAD AND TOBAGO': 'TT',
    'UNITED STATES': 'US',
    'UNITED STATES OF AMERICA': 'US',
    'USA': 'US',
    'URUGUAY': 'UY',
    'VENEZUELA': 'VE',
    
    # Asia
    'AFGHANISTAN': 'AF',
    'ARMENIA': 'AM',
    'AZERBAIJAN': 'AZ',
    'BAHRAIN': 'BH',
    'BANGLADESH': 'BD',
    'BHUTAN': 'BT',
    'BRUNEI': 'BN',
    'CAMBODIA': 'KH',
    'CHINA': 'CN',
    'CYPRUS': 'CY',
    'GEORGIA': 'GE',
    'INDIA': 'IN',
    'INDONESIA': 'ID',
    'IRAN': 'IR',
    'IRAQ': 'IQ',
    'ISRAEL': 'IL',
    'JAPAN': 'JP',
    'JORDAN': 'JO',
    'KAZAKHSTAN': 'KZ',
    'KUWAIT': 'KW',
    'KYRGYZSTAN': 'KG',
    'LAOS': 'LA',
    'LEBANON': 'LB',
    'MALAYSIA': 'MY',
    'MALDIVES': 'MV',
    'MONGOLIA': 'MN',
    'MYANMAR': 'MM',
    'BURMA': 'MM',
    'NEPAL': 'NP',
    'NORTH KOREA': 'KP',
    'OMAN': 'OM',
    'PAKISTAN': 'PK',
    'PALESTINE': 'PS',
    'PHILIPPINES': 'PH',
    'QATAR': 'QA',
    'SAUDI ARABIA': 'SA',
    'SINGAPORE': 'SG',
    'SOUTH KOREA': 'KR',
    'SRI LANKA': 'LK',
    'SYRIA': 'SY',
    'TAIWAN': 'TW',
    'TAJIKISTAN': 'TJ',
    'THAILAND': 'TH',
    'TIMOR-LESTE': 'TL',
    'TURKEY': 'TR',
    'TURKMENISTAN': 'TM',
    'UNITED ARAB EMIRATES': 'AE',
    'UAE': 'AE',
    'UZBEKISTAN': 'UZ',
    'VIETNAM': 'VN',
    'YEMEN': 'YE',
    
    # Europe
    'ALBANIA': 'AL',
    'ANDORRA': 'AD',
    'AUSTRIA': 'AT',
    'BELARUS': 'BY',
    'BELGIUM': 'BE',
    'BOSNIA AND HERZEGOVINA': 'BA',
    'BULGARIA': 'BG',
    'CROATIA': 'HR',
    'CZECH REPUBLIC': 'CZ',
    'DENMARK': 'DK',
    'ESTONIA': 'EE',
    'FINLAND': 'FI',
    'FRANCE': 'FR',
    'GERMANY': 'DE',
    'GREECE': 'GR',
    'HUNGARY': 'HU',
    'ICELAND': 'IS',
    'IRELAND': 'IE',
    'ITALY': 'IT',
    'KOSOVO': 'XK',
    'LATVIA': 'LV',
    'LIECHTENSTEIN': 'LI',
    'LITHUANIA': 'LT',
    'LUXEMBOURG': 'LU',
    'MACEDONIA': 'MK',
    'MALTA': 'MT',
    'MOLDOVA': 'MD',
    'MONACO': 'MC',
    'MONTENEGRO': 'ME',
    'NETHERLANDS': 'NL',
    'NORWAY': 'NO',
    'POLAND': 'PL',
    'PORTUGAL': 'PT',
    'ROMANIA': 'RO',
    'RUSSIA': 'RU',
    'SAN MARINO': 'SM',
    'SERBIA': 'RS',
    'SLOVAKIA': 'SK',
    'SLOVENIA': 'SI',
    'SPAIN': 'ES',
    'SWEDEN': 'SE',
    'SWITZERLAND': 'CH',
    'UKRAINE': 'UA',
    'UNITED KINGDOM': 'GB',
    'UK': 'GB',
    'VATICAN CITY': 'VA',
    
    # Oceania
    'AUSTRALIA': 'AU',
    'FIJI': 'FJ',
    'KIRIBATI': 'KI',
    'MARSHALL ISLANDS': 'MH',
    'MICRONESIA': 'FM',
    'NAURU': 'NR',
    'NEW ZEALAND': 'NZ',
    'PALAU': 'PW',
    'PAPUA NEW GUINEA': 'PG',
    'SAMOA': 'WS',
    'SOLOMON ISLANDS': 'SB',
    'TONGA': 'TO',
    'TUVALU': 'TV',
    'VANUATU': 'VU',
    
    # Common variations and alternative names
    'REPUBLIC OF SOUTH SUDAN': 'SS',
    'CÔTE D\'IVOIRE': 'CI',
    'COTE D\'IVOIRE': 'CI',
    'COTE DIVOIRE': 'CI',
    'DRC': 'CD',
    'CONGO DRC': 'CD',
    'CONGO-KINSHASA': 'CD',
    'CONGO-BRAZZAVILLE': 'CG',
    'REPUBLIC OF CONGO': 'CG',
    'CZECHIA': 'CZ',
    'NORTH MACEDONIA': 'MK',
    'EAST TIMOR': 'TL',
    'HOLLAND': 'NL',
    'GREAT BRITAIN': 'GB',
    'ENGLAND': 'GB',
    'SCOTLAND': 'GB',
    'WALES': 'GB',
    'NORTHERN IRELAND': 'GB',
}


def get_country_iso_code(country_name):
    """
    Convert country name to ISO code.
    
    Args:
        country_name: Country name in any format
        
    Returns:
        ISO 2-letter country code or original value if not found
    """
    if not country_name:
        return 'US'  # Default to US
    
    # If already a 2-letter code, return uppercase
    if len(country_name) == 2:
        return country_name.upper()
    
    # Try to find in mapping
    country_upper = str(country_name).upper().strip()
    return COUNTRY_NAME_TO_CODE.get(country_upper, country_name)