# Generated by Django 5.1.7 on 2025-04-28 02:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_performancesetting_performancemetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('health_insurance_plan', models.CharField(choices=[('NONE', 'No Coverage'), ('BASIC', 'Basic Coverage'), ('STANDARD', 'Standard Coverage'), ('PREMIUM', 'Premium Coverage'), ('FAMILY', 'Family Coverage')], default='NONE', max_length=20)),
                ('health_insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('health_insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('health_insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dental_insurance_plan', models.CharField(choices=[('NONE', 'No Coverage'), ('BASIC', 'Basic Coverage'), ('STANDARD', 'Standard Coverage'), ('PREMIUM', 'Premium Coverage'), ('FAMILY', 'Family Coverage')], default='NONE', max_length=20)),
                ('dental_insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('dental_insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dental_insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vision_insurance_plan', models.CharField(choices=[('NONE', 'No Coverage'), ('BASIC', 'Basic Coverage'), ('STANDARD', 'Standard Coverage'), ('PREMIUM', 'Premium Coverage'), ('FAMILY', 'Family Coverage')], default='NONE', max_length=20)),
                ('vision_insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('vision_insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vision_insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retirement_plan', models.CharField(choices=[('NONE', 'None'), ('401K', '401(k)'), ('ROTH_401K', 'Roth 401(k)'), ('IRA', 'Individual Retirement Account'), ('ROTH_IRA', 'Roth IRA'), ('PENSION', 'Pension Plan'), ('OTHER', 'Other Retirement Plan')], default='NONE', max_length=20)),
                ('retirement_contribution_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('employer_match_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('has_life_insurance', models.BooleanField(default=False)),
                ('life_insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('life_insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('life_insurance_coverage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('life_insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_disability_insurance', models.BooleanField(default=False)),
                ('disability_insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_insurance_coverage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disability_insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_fsa', models.BooleanField(default=False)),
                ('fsa_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_hsa', models.BooleanField(default=False)),
                ('hsa_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_hsa_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_benefits', models.JSONField(blank=True, default=dict)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_enrollment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Benefits',
                'verbose_name_plural': 'Benefits',
            },
        ),
    ]
