# Generated by Django 5.1.7 on 2025-04-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WISE', 'Wise'), ('STRIPE', 'Stripe'), ('PLAID', 'Plaid'), ('DLOCAL', 'DLocal'), ('PAYPAL', 'PayPal'), ('MERCADO_PAGO', 'Mercado Pago'), ('RAZORPAY', 'Razorpay'), ('IYZICO', 'iyzico'), ('M_PESA', 'M-Pesa')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='CountryPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary'), (4, 'Quaternary')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='banking.country')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.paymentgateway')),
            ],
            options={
                'verbose_name': 'Country Payment Gateway',
                'verbose_name_plural': 'Country Payment Gateways',
                'ordering': ['country', 'priority'],
                'unique_together': {('country', 'priority')},
            },
        ),
    ]
